projects:
  PokerApp API:
    schemaPath: apps/poker/api/src/graphql/schema.json
    includes:
      - apps/poker/api/src/graphql/includes/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: apps/poker/api/src/graphql/API.ts
        docsFilePath: apps/poker/api/src/graphql/includes
        region: eu-west-3
        apiId: yzbphvr6knbavfe4mbcql7gwoy
        maxDepth: 2
