cacheFolder: ./.yarn/cache

# logFilters:
#   - code: YN0002
#     level: "${FLEX_YARN_LOGFILTER_LEVEL-warning}"
#   - code: YN0013
#     level: "${FLEX_YARN_LOGFILTER_LEVEL-warning}"
#   - code: YN0019
#     level: "${FLEX_YARN_LOGFILTER_LEVEL-warning}"
#   - code: YN0060
#     level: "${FLEX_YARN_LOGFILTER_LEVEL-warning}"
#   - code: YN0060
#     level: "${FLEX_YARN_LOGFILTER_LEVEL-warning}"

nmHoistingLimits: none
# nmHoistingLimits: workspaces

# nodeLinker: node-modules
# nodeLinker: pnpm
nodeLinker: pnp

supportedArchitectures:
  cpu:
    - "${FLEX_YARN_ARCHITECTURE_CPU-current}"
  libc:
    - "${FLEX_YARN_ARCHITECTURE_LIBC-current}"
  os:
    - "${FLEX_YARN_ARCHITECTURE_OS-current}"

yarnPath: .yarn/releases/yarn-3.6.3.cjs
