export type Styles = {
  animateFromRight: string
  animateFromTop: string
  box: string
  boxHeader: string
  button: string
  column: string
  container: string
  dl: string
  field: string
  flexinessRoot: string
  fromRight: string
  fromTop: string
  hasBackgroundAdmin: string
  hasBackgroundCobalt: string
  hasBackgroundDanger: string
  hasBackgroundDebug: string
  hasBackgroundGrey: string
  hasBackgroundGreyDark: string
  hasBackgroundGreyLight: string
  hasBackgroundGreyLighter: string
  hasBackgroundInfo: string
  hasBackgroundPrimary: string
  hasBackgroundQuaternary: string
  hasBackgroundSecondary: string
  hasBackgroundSuccess: string
  hasBackgroundTertiary: string
  hasBackgroundTertiaryDark: string
  hasBackgroundTertiaryLight: string
  hasBackgroundWarning: string
  hasBackgroundWhite: string
  hasBorderRadius: string
  hasBorderRadiusLarge: string
  hasBorderRadiusSmall: string
  hasInheritedColor: string
  hasOverlay: string
  hasTextAdmin: string
  hasTextAdminInvert: string
  hasTextCentered: string
  hasTextCenteredDesktop: string
  hasTextCenteredDesktopOnly: string
  hasTextCenteredFullhd: string
  hasTextCenteredMobile: string
  hasTextCenteredTablet: string
  hasTextCenteredTabletOnly: string
  hasTextCenteredTouch: string
  hasTextCenteredWidescreen: string
  hasTextCenteredWidescreenOnly: string
  hasTextCobalt: string
  hasTextCobaltInvert: string
  hasTextDanger: string
  hasTextDangerInvert: string
  hasTextDebug: string
  hasTextDebugInvert: string
  hasTextGrey: string
  hasTextGreyDark: string
  hasTextGreyLight: string
  hasTextGreyLighter: string
  hasTextInfo: string
  hasTextInfoInvert: string
  hasTextJustified: string
  hasTextJustifiedDesktop: string
  hasTextJustifiedDesktopOnly: string
  hasTextJustifiedFullhd: string
  hasTextJustifiedMobile: string
  hasTextJustifiedTablet: string
  hasTextJustifiedTabletOnly: string
  hasTextJustifiedTouch: string
  hasTextJustifiedWidescreen: string
  hasTextJustifiedWidescreenOnly: string
  hasTextLeft: string
  hasTextLeftDesktop: string
  hasTextLeftDesktopOnly: string
  hasTextLeftFullhd: string
  hasTextLeftMobile: string
  hasTextLeftTablet: string
  hasTextLeftTabletOnly: string
  hasTextLeftTouch: string
  hasTextLeftWidescreen: string
  hasTextLeftWidescreenOnly: string
  hasTextPrimary: string
  hasTextPrimaryInvert: string
  hasTextQuaternary: string
  hasTextQuaternaryInvert: string
  hasTextRight: string
  hasTextRightDesktop: string
  hasTextRightDesktopOnly: string
  hasTextRightFullhd: string
  hasTextRightMobile: string
  hasTextRightTablet: string
  hasTextRightTabletOnly: string
  hasTextRightTouch: string
  hasTextRightWidescreen: string
  hasTextRightWidescreenOnly: string
  hasTextSecondary: string
  hasTextSecondaryInvert: string
  hasTextSuccess: string
  hasTextSuccessInvert: string
  hasTextTertiary: string
  hasTextTertiaryDark: string
  hasTextTertiaryDarkInvert: string
  hasTextTertiaryInvert: string
  hasTextTertiaryLight: string
  hasTextTertiaryLightInvert: string
  hasTextWarning: string
  hasTextWarningInvert: string
  hasTextWeightBold: string
  hasTextWeightExtrabold: string
  hasTextWeightLight: string
  hasTextWeightMedium: string
  hasTextWeightNormal: string
  hasTextWeightSemibold: string
  hasTextWhite: string
  hasTextWhiteInvert: string
  hasVariant: string
  hasWireframes: string
  heroBody: string
  icon: string
  iconList: string
  input: string
  isAdmin: string
  isAlignContentBaseline: string
  isAlignContentCenter: string
  isAlignContentEnd: string
  isAlignContentFlexEnd: string
  isAlignContentFlexStart: string
  isAlignContentSpaceAround: string
  isAlignContentSpaceBetween: string
  isAlignContentSpaceEvenly: string
  isAlignContentStart: string
  isAlignContentStretch: string
  isAlignItemsBaseline: string
  isAlignItemsCenter: string
  isAlignItemsEnd: string
  isAlignItemsFlexEnd: string
  isAlignItemsFlexStart: string
  isAlignItemsSelfEnd: string
  isAlignItemsSelfStart: string
  isAlignItemsStart: string
  isAlignItemsStretch: string
  isAlignSelfAuto: string
  isAlignSelfBaseline: string
  isAlignSelfCenter: string
  isAlignSelfFlexEnd: string
  isAlignSelfFlexStart: string
  isAlignSelfStretch: string
  isAlternate: string
  isBlock: string
  isBlockDesktop: string
  isBlockDesktopOnly: string
  isBlockFullhd: string
  isBlockMobile: string
  isBlockTablet: string
  isBlockTabletOnly: string
  isBlockTouch: string
  isBlockWidescreen: string
  isBlockWidescreenOnly: string
  isBordered: string
  isCapitalized: string
  isCenteredDesktop: string
  isCenteredMobile: string
  isCenteredTablet: string
  isCheckradio: string
  isClearfix: string
  isClipped: string
  isFlex: string
  isFlexDesktop: string
  isFlexDesktopOnly: string
  isFlexDirectionColumn: string
  isFlexDirectionColumnReverse: string
  isFlexDirectionRow: string
  isFlexDirectionRowReverse: string
  isFlexFullhd: string
  isFlexGrow_0: string
  isFlexGrow_1: string
  isFlexGrow_2: string
  isFlexGrow_3: string
  isFlexGrow_4: string
  isFlexGrow_5: string
  isFlexMobile: string
  isFlexShrink_0: string
  isFlexShrink_1: string
  isFlexShrink_2: string
  isFlexShrink_3: string
  isFlexShrink_4: string
  isFlexShrink_5: string
  isFlexTablet: string
  isFlexTabletOnly: string
  isFlexTouch: string
  isFlexWidescreen: string
  isFlexWidescreenOnly: string
  isFlexWrapNowrap: string
  isFlexWrapWrap: string
  isFlexWrapWrapReverse: string
  isFullheight: string
  isFullwidth: string
  isFullwidthMobile: string
  isGap_1: string
  isGap_2: string
  isGap_3: string
  isGap_4: string
  isGap_5: string
  isGap_6: string
  isGap_7: string
  isHidden: string
  isHiddenDesktop: string
  isHiddenDesktopOnly: string
  isHiddenFullhd: string
  isHiddenMobile: string
  isHiddenTablet: string
  isHiddenTabletOnly: string
  isHiddenTouch: string
  isHiddenWidescreen: string
  isHiddenWidescreenOnly: string
  isInline: string
  isInlineBlock: string
  isInlineBlockDesktop: string
  isInlineBlockDesktopOnly: string
  isInlineBlockFullhd: string
  isInlineBlockMobile: string
  isInlineBlockTablet: string
  isInlineBlockTabletOnly: string
  isInlineBlockTouch: string
  isInlineBlockWidescreen: string
  isInlineBlockWidescreenOnly: string
  isInlineDesktop: string
  isInlineDesktopOnly: string
  isInlineFlex: string
  isInlineFlexDesktop: string
  isInlineFlexDesktopOnly: string
  isInlineFlexFullhd: string
  isInlineFlexMobile: string
  isInlineFlexTablet: string
  isInlineFlexTabletOnly: string
  isInlineFlexTouch: string
  isInlineFlexWidescreen: string
  isInlineFlexWidescreenOnly: string
  isInlineFullhd: string
  isInlineMobile: string
  isInlineTablet: string
  isInlineTabletOnly: string
  isInlineTouch: string
  isInlineWidescreen: string
  isInlineWidescreenOnly: string
  isInvisible: string
  isInvisibleDesktop: string
  isInvisibleDesktopOnly: string
  isInvisibleFullhd: string
  isInvisibleMobile: string
  isInvisibleTablet: string
  isInvisibleTabletOnly: string
  isInvisibleTouch: string
  isInvisibleWidescreen: string
  isInvisibleWidescreenOnly: string
  isItalic: string
  isJustifiedCenter: string
  isJustifiedCenterDesktop: string
  isJustifiedCenterDesktopOnly: string
  isJustifiedCenterFullhd: string
  isJustifiedCenterMobile: string
  isJustifiedCenterTablet: string
  isJustifiedCenterTabletOnly: string
  isJustifiedCenterTouch: string
  isJustifiedCenterWidescreen: string
  isJustifiedCenterWidescreenOnly: string
  isJustifiedEnd: string
  isJustifiedEndDesktop: string
  isJustifiedEndDesktopOnly: string
  isJustifiedEndFullhd: string
  isJustifiedEndMobile: string
  isJustifiedEndTablet: string
  isJustifiedEndTabletOnly: string
  isJustifiedEndTouch: string
  isJustifiedEndWidescreen: string
  isJustifiedEndWidescreenOnly: string
  isJustifiedStart: string
  isJustifiedStartDesktop: string
  isJustifiedStartDesktopOnly: string
  isJustifiedStartFullhd: string
  isJustifiedStartMobile: string
  isJustifiedStartTablet: string
  isJustifiedStartTabletOnly: string
  isJustifiedStartTouch: string
  isJustifiedStartWidescreen: string
  isJustifiedStartWidescreenOnly: string
  isJustifyContentCenter: string
  isJustifyContentEnd: string
  isJustifyContentFlexEnd: string
  isJustifyContentFlexStart: string
  isJustifyContentLeft: string
  isJustifyContentRight: string
  isJustifyContentSpaceAround: string
  isJustifyContentSpaceBetween: string
  isJustifyContentSpaceEvenly: string
  isJustifyContentStart: string
  isLoaded: string
  isLoading: string
  isLowercase: string
  isMarginless: string
  isMultiline: string
  isOverlay: string
  isPaddingless: string
  isPulledLeft: string
  isPulledRight: string
  isRadiusless: string
  isRounded: string
  isShadowless: string
  isSize_1: string
  isSize_1Desktop: string
  isSize_1Fullhd: string
  isSize_1Mobile: string
  isSize_1Tablet: string
  isSize_1Touch: string
  isSize_1Widescreen: string
  isSize_2: string
  isSize_2Desktop: string
  isSize_2Fullhd: string
  isSize_2Mobile: string
  isSize_2Tablet: string
  isSize_2Touch: string
  isSize_2Widescreen: string
  isSize_3: string
  isSize_3Desktop: string
  isSize_3Fullhd: string
  isSize_3Mobile: string
  isSize_3Tablet: string
  isSize_3Touch: string
  isSize_3Widescreen: string
  isSize_4: string
  isSize_4Desktop: string
  isSize_4Fullhd: string
  isSize_4Mobile: string
  isSize_4Tablet: string
  isSize_4Touch: string
  isSize_4Widescreen: string
  isSize_5: string
  isSize_5Desktop: string
  isSize_5Fullhd: string
  isSize_5Mobile: string
  isSize_5Tablet: string
  isSize_5Touch: string
  isSize_5Widescreen: string
  isSize_6: string
  isSize_6Desktop: string
  isSize_6Fullhd: string
  isSize_6Mobile: string
  isSize_6Tablet: string
  isSize_6Touch: string
  isSize_6Widescreen: string
  isSize_7: string
  isSize_7Desktop: string
  isSize_7Fullhd: string
  isSize_7Mobile: string
  isSize_7Tablet: string
  isSize_7Touch: string
  isSize_7Widescreen: string
  isSize_8: string
  isSize_8Desktop: string
  isSize_8Fullhd: string
  isSize_8Mobile: string
  isSize_8Tablet: string
  isSize_8Touch: string
  isSize_8Widescreen: string
  isUnderline: string
  isUnselectable: string
  isUppercase: string
  isVcentered: string
  isVcenteredDesktop: string
  isVcenteredMobile: string
  isVcenteredTablet: string
  isWireframe: string
  loadingPulse: string
  mainContent: string
  paragraph: string
  placeHolderShimmer: string
  section: string
  spinAround: string
  suptitle: string
  text: string
  title: string
}

export type ClassNames = keyof Styles

declare const styles: Styles

export default styles
