export type Styles = {
  accordion: string;
  accordionBody: string;
  accordionContent: string;
  accordionHeader: string;
  accordions: string;
  accordionTitle: string;
  animateFromRight: string;
  animateFromTop: string;
  button: string;
  field: string;
  flexinessRoot: string;
  fromRight: string;
  fromTop: string;
  input: string;
  isActive: string;
  isAdmin: string;
  isBordered: string;
  isBoxed: string;
  isCheckradio: string;
  isCobalt: string;
  isDanger: string;
  isDebug: string;
  isGrouped: string;
  isInfo: string;
  isLarge: string;
  isMedium: string;
  isPrimary: string;
  isQuaternary: string;
  isSecondary: string;
  isSmall: string;
  isStatic: string;
  isSuccess: string;
  isTertiary: string;
  isTertiaryDark: string;
  isTertiaryLight: string;
  isWarning: string;
  isWhite: string;
  placeHolderShimmer: string;
  select: string;
  spinAround: string;
  tag: string;
  title: string;
  toggle: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
