export type Styles = {
  animateFromRight: string;
  animateFromTop: string;
  badge: string;
  bgConnected: string;
  burgerMenu: string;
  column: string;
  container: string;
  control: string;
  field: string;
  flexinessRoot: string;
  flexiUiSearch: string;
  fromRight: string;
  fromTop: string;
  hasDropdownArrow: string;
  hasDynamicPlaceholder: string;
  hasEndingArrow: string;
  hasTextPrimary: string;
  icon: string;
  input: string;
  inputDynamicPlaceholder: string;
  isActive: string;
  isAlternate: string;
  isFirst: string;
  isFluid: string;
  isFourth: string;
  isHighlighted: string;
  isHoverable: string;
  isInfo: string;
  isLarge: string;
  isMedium: string;
  isMegadropdownParent: string;
  isNew: string;
  isNpm: string;
  isRightAligned: string;
  isSecond: string;
  isSecondary: string;
  isSmall: string;
  isStacked: string;
  isSticky: string;
  isSuccess: string;
  isUp: string;
  login: string;
  menu: string;
  menuClose: string;
  menuOpen: string;
  navbar: string;
  navbarBrand: string;
  navbarCategoryTitle: string;
  navbarDivider: string;
  navbarDropdown: string;
  navbarDropdownClose: string;
  navbarDropdownSection: string;
  navbarEnd: string;
  navbarExtras: string;
  navbarIcons: string;
  navbarItem: string;
  navbarItemAccordion: string;
  navbarItemAccordionBack: string;
  navbarItemAccordionContent: string;
  navbarItemAccordionHeader: string;
  navbarItemAccordionTitle: string;
  navbarLink: string;
  navbarLinks: string;
  navbarMenu: string;
  navbarStart: string;
  navbarTitle: string;
  placeHolderShimmer: string;
  spinAround: string;
  title: string;
  user: string;
  userMenu: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
