export type Styles = {
  animateFromRight: string;
  animateFromTop: string;
  box: string;
  boxContent: string;
  boxFooter: string;
  boxHeader: string;
  flexinessRoot: string;
  fromRight: string;
  fromTop: string;
  hasBackground: string;
  hasHat: string;
  isAdmin: string;
  isChild: string;
  isCobalt: string;
  isDanger: string;
  isDebug: string;
  isFlat: string;
  isFlatPrimary: string;
  isFlatQuaternary: string;
  isFlatSecondary: string;
  isFlatTertiary: string;
  isFullheight: string;
  isGrey: string;
  isHat: string;
  isInfo: string;
  isInverted: string;
  isParent: string;
  isPrimary: string;
  isQuaternary: string;
  isSecondary: string;
  isSuccess: string;
  isTertiary: string;
  isTertiaryDark: string;
  isTertiaryLight: string;
  isTransparent: string;
  isUnboxed: string;
  isVertical: string;
  isWarning: string;
  isWhite: string;
  paragraph: string;
  placeHolderShimmer: string;
  spinAround: string;
  subtitle: string;
  text: string;
  tile: string;
  tilesContainer: string;
  title: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
