export type Styles = {
  animateFromRight: string;
  animateFromTop: string;
  button: string;
  control: string;
  dropdownTrigger: string;
  fa: string;
  field: string;
  fieldBody: string;
  fieldLabel: string;
  file: string;
  fileCta: string;
  fileIcon: string;
  fileInput: string;
  fileLabel: string;
  fileName: string;
  flexinessRoot: string;
  fromRight: string;
  fromTop: string;
  hasAddons: string;
  hasAddonsCentered: string;
  hasAddonsFullwidth: string;
  hasAddonsRight: string;
  hasDynamicPlaceholder: string;
  hasIcon: string;
  hasIconRight: string;
  hasIconsLeft: string;
  hasIconsRight: string;
  hasName: string;
  hasPasswordDiscover: string;
  help: string;
  icon: string;
  input: string;
  isActive: string;
  isAdmin: string;
  isBoxed: string;
  isCentered: string;
  isCobalt: string;
  isDanger: string;
  isDebug: string;
  isEmpty: string;
  isExpanded: string;
  isFocused: string;
  isFullwidth: string;
  isGrouped: string;
  isGroupedCentered: string;
  isGroupedMultiline: string;
  isGroupedRight: string;
  isHorizontal: string;
  isHovered: string;
  isInfo: string;
  isLarge: string;
  isLoading: string;
  isLong: string;
  isMedium: string;
  isMobile: string;
  isNarrow: string;
  isNormal: string;
  isPrimary: string;
  isQuaternary: string;
  isRight: string;
  isSearching: string;
  isSecondary: string;
  isShort: string;
  isSmall: string;
  isSuccess: string;
  isTertiary: string;
  isTertiaryDark: string;
  isTertiaryLight: string;
  isVeryLong: string;
  isVeryShort: string;
  isWarning: string;
  isWhite: string;
  label: string;
  placeHolderShimmer: string;
  select: string;
  spinAround: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
