export type Styles = {
  animateFromRight: string;
  animateFromTop: string;
  bellbounce: string;
  bellring: string;
  button: string;
  flexiFaciliti: string;
  flexiHandicapzero: string;
  flexiLaFibre: string;
  flexinessRoot: string;
  flexiNotificationBottom: string;
  flexiNotificationTop: string;
  flexiPaymentCb: string;
  flexiPaymentMastercard: string;
  flexiPaymentPaypal: string;
  flexiPaymentVisa: string;
  fromRight: string;
  fromTop: string;
  hasStatus: string;
  icon: string;
  iconAndText: string;
  isAdmin: string;
  isAlternate: string;
  isAncestor: string;
  isAnimated: string;
  isBottom: string;
  isBottomRight: string;
  isCircled: string;
  isCircledAdmin: string;
  isCircledCobalt: string;
  isCircledDanger: string;
  isCircledDebug: string;
  isCircledGrey: string;
  isCircledGreyDark: string;
  isCircledGreyLight: string;
  isCircledGreyLighter: string;
  isCircledInfo: string;
  isCircledPrimary: string;
  isCircledQuaternary: string;
  isCircledSecondary: string;
  isCircledSuccess: string;
  isCircledTertiary: string;
  isCircledTertiaryDark: string;
  isCircledTertiaryLight: string;
  isCircledWarning: string;
  isCircledWhite: string;
  isCobalt: string;
  isDanger: string;
  isDebug: string;
  isDescendant: string;
  isGrey: string;
  isGreyDark: string;
  isGreyLight: string;
  isGreyLighter: string;
  isHuge: string;
  isInfo: string;
  isLarge: string;
  isMedium: string;
  isPrimary: string;
  isQuaternary: string;
  isSecondary: string;
  isSmall: string;
  isStacked: string;
  isStackedDesktop: string;
  isStackedMobile: string;
  isStackedTablet: string;
  isStackedWidescreen: string;
  isStretched: string;
  isSuccess: string;
  isTertiary: string;
  isTertiaryDark: string;
  isTertiaryLight: string;
  isTop: string;
  isWarning: string;
  isWhite: string;
  placeHolderShimmer: string;
  spinAround: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
