export type Styles = {
  accordion: string
  accordionBody: string
  accordionContent: string
  accordionHeader: string
  accordions: string
  accordionTitle: string
  active: string
  animateFromRight: string
  animateFromTop: string
  arrow: string
  asideMenuList: string
  badge: string
  badgeAndText: string
  bellbounce: string
  bellring: string
  bgConnected: string
  bLazy: string
  bLoaded: string
  block: string
  body: string
  box: string
  boxContent: string
  boxFooter: string
  boxHeader: string
  breadcrumb: string
  burgerMenu: string
  button: string
  buttons: string
  bytelFooter: string
  callToAction: string
  card: string
  cardContent: string
  cardFooter: string
  cardHeader: string
  cardHeaderContent: string
  cardHeaderIcon: string
  cardHeaderTitle: string
  cardImage: string
  cardTitle: string
  centimes: string
  cents: string
  chatContent: string
  chatMessage: string
  chatMessageAvatar: string
  chatMessageContent: string
  chatMessages: string
  chatWindow: string
  chatWindowInput: string
  close: string
  column: string
  columns: string
  container: string
  control: string
  count: string
  countdown: string
  delete: string
  description: string
  details: string
  disclaimer: string
  disclaimerContent: string
  disclaimerHeader: string
  disclaimerItem: string
  disclaimerMarker: string
  dl: string
  dot: string
  dropdown: string
  dropdownContent: string
  dropdownDivider: string
  dropdownItem: string
  dropdownMenu: string
  dropdownMenuList: string
  dropdownTrigger: string
  fa: string
  field: string
  fieldBody: string
  fieldLabel: string
  file: string
  fileCta: string
  fileIcon: string
  fileInput: string
  fileLabel: string
  fileName: string
  flexi_4g: string
  flexi_4g_5g: string
  flexi_4g_5gPlus: string
  flexi_4G4Gplus: string
  flexi_4gPlus: string
  flexi_5g: string
  flexiAccessibility: string
  flexiAccomodation: string
  flexiAddcalendarRdv: string
  flexiAdvisor: string
  flexiAfrica: string
  flexiAirTravel: string
  flexiArchiving: string
  flexiArtificialIntelligence: string
  flexiArtistChair: string
  flexiAt: string
  flexiAtCheckS: string
  flexiAtCogsCircle: string
  flexiAtExclamationCircle: string
  flexiAtGlobe: string
  flexiAtInfinityCircle: string
  flexiAtInfo: string
  flexiAtPlusCircle: string
  flexiAtUnavailable: string
  flexiAudioVisual: string
  flexiAutoplan: string
  flexiBabyphone: string
  flexiBadges: string
  flexiBall: string
  flexiBank: string
  flexiBarcodeSearch: string
  flexiBattery: string
  flexiBduo: string
  flexiBeautician: string
  flexiBellRinging: string
  flexiBluetooth: string
  flexiBox: string
  flexiBox_4g: string
  flexiBoxAdd: string
  flexiBoxCheckCircle: string
  flexiBoxCheckCircleS: string
  flexiBoxEole: string
  flexiBoxExclamationCircle: string
  flexiBoxFaq: string
  flexiBoxInfoCircle: string
  flexiBoxInfoCogs: string
  flexiBoxMobile: string
  flexiBoxRedo: string
  flexiBoxSmartTv: string
  flexiBoxStethoscope: string
  flexiBoxUnavailable: string
  flexiBtv: string
  flexiBtvIllimite: string
  flexiBtvplus: string
  flexiBusinessTrip: string
  flexiCalendar: string
  flexiCalendarClockCircle: string
  flexiCalendarCogsCircle: string
  flexiCalendarExclamationCircle: string
  flexiCalendarInfoCircle: string
  flexiCalendarPlusCircle: string
  flexiCalendarQuestionCircle: string
  flexiCalendarUnavailable: string
  flexiCamera: string
  flexiCarPark: string
  flexiCarpooling: string
  flexiCarRent: string
  flexiCatering: string
  flexiCheck: string
  flexiCheckCircle: string
  flexiChildrenAccess: string
  flexiChip: string
  flexiClapperboard: string
  flexiCleanSurface: string
  flexiClickCollect_2h: string
  flexiClipboardChecklist: string
  flexiClosed: string
  flexiCloud: string
  flexiCloud_100go: string
  flexiCloud_20go: string
  flexiCloud_30go: string
  flexiCloud_50go: string
  flexiCloud_70go: string
  flexiCloudCheck: string
  flexiCloudCheckS: string
  flexiCloudCogsCircle: string
  flexiCloudExclamationCircle: string
  flexiCloudGlobe: string
  flexiCloudInfinity: string
  flexiCloudPlusCircle: string
  flexiCloudSave: string
  flexiCo2Emission: string
  flexiCogs: string
  flexiCollaborativeLibrary: string
  flexiComment: string
  flexiCommentEarth: string
  flexiCommentExclamationCircle: string
  flexiCommentEye: string
  flexiCommentQuestion: string
  flexiCommentsQuestionDots: string
  flexiCommentVoicemail: string
  flexiCommunity: string
  flexiConcierge: string
  flexiContact: string
  flexiContactlessPayment: string
  flexiCorporateCard: string
  flexiCourier: string
  flexiCreditCard: string
  flexiCreditCardAccepted: string
  flexiCreditCardLock: string
  flexiCreditCards: string
  flexiCreditCards_12: string
  flexiCripplingDisease: string
  flexiCse: string
  flexiDesktop: string
  flexiDiagnostic: string
  flexiDistance: string
  flexiDontTouch: string
  flexiDuplicata: string
  flexiEarSlash: string
  flexiEarth: string
  flexiEcoConception: string
  flexiEcommerceProductReturn: string
  flexiEcommercePromoLabel: string
  flexiEcoresponsibleDigital: string
  flexiElectricalOverload: string
  flexiElectricalPlug: string
  flexiElectricCar: string
  flexiEnergy: string
  flexiEnergyOptimization: string
  flexiEnvelope: string
  flexiEnvelopePlusCircle: string
  flexiEnvironmentalFootprint: string
  flexiEsim: string
  flexiEthics: string
  flexiEurope: string
  flexiEuros: string
  flexiExclamation: string
  flexiExclamationCircle: string
  flexiExclamationRedo: string
  flexiExclamationTriangle: string
  flexiFacemask_1: string
  flexiFacemask_2: string
  flexiFaciliti: string
  flexiFileAttached: string
  flexiFileEuro: string
  flexiFileEuroCheckCircle: string
  flexiFileEuroCheckCircleS: string
  flexiFileEuroExclamationCircle: string
  flexiFileEuroInfoCircle: string
  flexiFileEuroLockCircle: string
  flexiFileEuroQuestionCircle: string
  flexiFileList: string
  flexiFileManagement: string
  flexiFileNew: string
  flexiFilePdf: string
  flexiFilm: string
  flexiFingerprint: string
  flexiFirstRuralArea: string
  flexiFlashSell: string
  flexiFlexymoovBicycle: string
  flexiFlowerOrder: string
  flexiFrance: string
  flexiFranceMarker: string
  flexiFrown: string
  flexiGamepad: string
  flexiGamesConsole: string
  flexiGauge: string
  flexiGaugeCogsCircle: string
  flexiGaugeExclamationCircle: string
  flexiGaugePlusCircle: string
  flexiGift: string
  flexiGoodPractices: string
  flexiHairdresser: string
  flexiHandicapzero: string
  flexiHandMobile: string
  flexiHandsfree: string
  flexiHandsHelping: string
  flexiHandTools: string
  flexiHeadphones: string
  flexiHeart: string
  flexiHome: string
  flexiHomeTools: string
  flexiHotspot: string
  flexiHourglass: string
  flexiHydroGel: string
  flexiIdentity: string
  flexiImmersiveContentGlass: string
  flexiImmersiveContentPeople: string
  flexiInternalFraud: string
  flexiIot: string
  flexiIp: string
  flexiLaFibre: string
  flexiLaptop: string
  flexiLaptopTabletMobile: string
  flexiLightbulbOn: string
  flexiLinesSpeed: string
  flexiLink: string
  flexiLinkCopy: string
  flexiLock: string
  flexiMail: string
  flexiMailboxMarker: string
  flexiMaker: string
  flexiMapMarker: string
  flexiMarker: string
  flexiMassage: string
  flexiMentalDisability: string
  flexiMentalHandicap: string
  flexiMicrowaves: string
  flexiMobile: string
  flexiMobile_06Slash: string
  flexiMobile_07Slash: string
  flexiMobile_08Slash: string
  flexiMobileBan: string
  flexiMobileBroken: string
  flexiMobileCloud: string
  flexiMobileComment: string
  flexiMobileEuro: string
  flexiMobileEye: string
  flexiMobileGlobe: string
  flexiMobileHand: string
  flexiMobileInfinity: string
  flexiMobileLock: string
  flexiMobilePercentage: string
  flexiMobilePlusSimCards: string
  flexiMobileReconditioned: string
  flexiMobileRecovery: string
  flexiMobileSync: string
  flexiMobileTools: string
  flexiMobileUpDown: string
  flexiModem_3g: string
  flexiMotivation: string
  flexiMouse: string
  flexiMovingPersonsGoods: string
  flexinessAsserted: string
  flexinessRoot: string
  flexiNetwork: string
  flexiNetworkAntenna: string
  flexiNewspapers: string
  flexiNotebookTarifs: string
  flexiNotes: string
  flexiNotificationBottom: string
  flexiNotificationTop: string
  flexiOfficeSupply: string
  flexiOptician: string
  flexiPackagePreparation: string
  flexiPaperclip: string
  flexiParcel: string
  flexiPause: string
  flexiPaymentAmericanexpress: string
  flexiPaymentCb: string
  flexiPaymentMastercard: string
  flexiPaymentPaypal: string
  flexiPaymentVisa: string
  flexiPersonDoor: string
  flexiPhone: string
  flexiPhoneAfrica: string
  flexiPhoneBurger: string
  flexiPhoneEuro: string
  flexiPhoneEurope: string
  flexiPhoneGlobe: string
  flexiPhoneIncomingCall: string
  flexiPhoneInfinity: string
  flexiPhoneNotes: string
  flexiPhoneOutgoingCall: string
  flexiPhonePlusSimCard: string
  flexiPhoneSwitzerland: string
  flexiPhysicalDisability: string
  flexiPictoFaciliti: string
  flexiPictoHandicapzero: string
  flexiPictoLaFibre: string
  flexiPictoPaymentCb: string
  flexiPictoPaymentMastercard: string
  flexiPictoPaymentPaypal: string
  flexiPictoPaymentVisa: string
  flexiPlayBeginning: string
  flexiPlayCircle: string
  flexiPlexiExchange: string
  flexiPlugCheck: string
  flexiPlus: string
  flexiPlusCircle: string
  flexiPrinter: string
  flexiPrintingStationery: string
  flexiPriorityPath: string
  flexiRecycle: string
  flexiRedo: string
  flexiRedo_14Days: string
  flexiRedo_30Days: string
  flexiRedo_7Days: string
  flexiReduceCo2Emission: string
  flexiRemote: string
  flexiRepeater: string
  flexiRepeaterAlt: string
  flexiRestrictedArea: string
  flexiRingtoneWelcomeSound: string
  flexiRotation_360: string
  flexiRules: string
  flexiSamples: string
  flexiSamplesCogsCircle: string
  flexiSamplesExclamationMarkCircle: string
  flexiSamplesPlusCircle: string
  flexiSatelliteAntenna: string
  flexiScan: string
  flexiSdCard: string
  flexiSearch: string
  flexiSecurityHealth: string
  flexiShield: string
  flexiShieldAt: string
  flexiShieldCheck: string
  flexiShieldExclamation: string
  flexiShieldPrivateLife: string
  flexiShootingStar: string
  flexiShoppingBag: string
  flexiSimCard: string
  flexiSimCardRedo: string
  flexiSimCards: string
  flexiSimCardUnlock: string
  flexiSmile: string
  flexiSmileNocircled: string
  flexiSmilePlus: string
  flexiSmsInfo: string
  flexiSocialFacebook: string
  flexiSocialInstagram: string
  flexiSocialTwitter: string
  flexiSocialYoutube: string
  flexiSports: string
  flexiSteeringWheel: string
  flexiStopwatch: string
  flexiStopwatch_2h: string
  flexiStopwatchClickCollect: string
  flexiStopwatchClickCollect_2h: string
  flexiStore: string
  flexiStoreLocator: string
  flexiSunEuro: string
  flexiSustainableDevelopment: string
  flexiSync: string
  flexiTablet: string
  flexiTeamMeal: string
  flexiTh: string
  flexiThunderRedo: string
  flexiTimes: string
  flexiTimesCircle: string
  flexiTools: string
  flexiTopNews: string
  flexiTrainingDiploma: string
  flexiTransport: string
  flexiTrash: string
  flexiTravelAgency: string
  flexiTravelPolicies: string
  flexiTruck: string
  flexiTruckSpeed: string
  flexiTurkey: string
  flexiTv: string
  flexiTv_4k: string
  flexiTv_8k: string
  flexiTvBtv: string
  flexiTvCurved: string
  flexiTvHd: string
  flexiTvInfinity: string
  flexiTvMulti: string
  flexiTvMultiOpticalFiber: string
  flexiTvVod: string
  flexiUiArrowDown: string
  flexiUiArrowDownR: string
  flexiUiArrowLeft: string
  flexiUiArrowLeftR: string
  flexiUiArrowRight: string
  flexiUiArrowRightR: string
  flexiUiArrowUp: string
  flexiUiArrowUpR: string
  flexiUiBell: string
  flexiUiCheck: string
  flexiUiCheckCircle: string
  flexiUiCheckCircleS: string
  flexiUiCheckR: string
  flexiUiDownload: string
  flexiUiEnvelope: string
  flexiUiExclamation: string
  flexiUiExclamationCircle: string
  flexiUiExclamationCircleS: string
  flexiUiExclamationR: string
  flexiUiEye: string
  flexiUiEyeS: string
  flexiUiEyeSlash: string
  flexiUiEyeSlashS: string
  flexiUiHome: string
  flexiUiInfo: string
  flexiUiInfoCircle: string
  flexiUiInfoCircleR: string
  flexiUiLogo: string
  flexiUiMarker: string
  flexiUiMarkerS: string
  flexiUiMenu: string
  flexiUiMinus: string
  flexiUiMinusCircle: string
  flexiUiPauseS: string
  flexiUiPencil: string
  flexiUiPencilS: string
  flexiUiPlayS: string
  flexiUiPlus: string
  flexiUiPlusCircle: string
  flexiUiPlusCircleR: string
  flexiUiPlusCircleS: string
  flexiUiPlusR: string
  flexiUiPower: string
  flexiUiQuestion: string
  flexiUiQuestionCircle: string
  flexiUiQuestionCircleR: string
  flexiUiRelaisColisExpress: string
  flexiUiSearch: string
  flexiUiSearchR: string
  flexiUiShoppingBag: string
  flexiUiShoppingCart: string
  flexiUiSliders: string
  flexiUiStar: string
  flexiUiStarHalf: string
  flexiUiStarS: string
  flexiUiTimes: string
  flexiUiTimesCircle: string
  flexiUiTimesCircleR: string
  flexiUiTimesCircleS: string
  flexiUiTimesR: string
  flexiUiTrash: string
  flexiUiTrashS: string
  flexiUiUpload: string
  flexiUiUser: string
  flexiUnavailable: string
  flexiUnlimited: string
  flexiUsbkey: string
  flexiUser: string
  flexiUserHeadset: string
  flexiUsers: string
  flexiUsersShieldS: string
  flexiUsersShieldStarS: string
  flexiUserTie: string
  flexiVictory: string
  flexiVisor: string
  flexiVisuallyImpaired: string
  flexiVoiceAssistance: string
  flexiVoicemail: string
  flexiVolumeOff: string
  flexiVolumeOn: string
  flexiVSign: string
  flexiVtcTaxiMotorbike: string
  flexiWall: string
  flexiWasteReduction: string
  flexiWatch: string
  flexiWebcam: string
  flexiWifi: string
  flexiWifiLow: string
  flexiWifiMedium: string
  flexiWindow: string
  flexiWorkplaceLayout: string
  flexiWorkshop: string
  footer: string
  fromRight: string
  fromTop: string
  hasAddons: string
  hasAddonsCentered: string
  hasAddonsFullwidth: string
  hasAddonsRight: string
  hasArrowSeparator: string
  hasBackground: string
  hasBackgroundAdmin: string
  hasBackgroundCobalt: string
  hasBackgroundDanger: string
  hasBackgroundDebug: string
  hasBackgroundGrey: string
  hasBackgroundGreyDark: string
  hasBackgroundGreyLight: string
  hasBackgroundGreyLighter: string
  hasBackgroundInfo: string
  hasBackgroundPrimary: string
  hasBackgroundQuaternary: string
  hasBackgroundSecondary: string
  hasBackgroundSuccess: string
  hasBackgroundTertiary: string
  hasBackgroundTertiaryDark: string
  hasBackgroundTertiaryLight: string
  hasBackgroundWarning: string
  hasBackgroundWhite: string
  hasBgGradient: string
  hasBgImage: string
  hasBody: string
  hasBorderRadius: string
  hasBorderRadiusLarge: string
  hasBorderRadiusSmall: string
  hasBulletSeparator: string
  hasDescription: string
  hasDotSeparator: string
  hasDropdownArrow: string
  hasDynamicPlaceholder: string
  hasEndingArrow: string
  hasFixedSize: string
  hasHat: string
  hasHatDesktop: string
  hasHatMobile: string
  hasHatTablet: string
  hasIcon: string
  hasIconLeft: string
  hasIconRight: string
  hasIconsLeft: string
  hasIconsRight: string
  hasInheritedColor: string
  hasLongCta: string
  hasMixins: string
  hasName: string
  hasOverlap: string
  hasOverlay: string
  hasPasswordDiscover: string
  hasPatternLight: string
  hasSlice: string
  hasStatus: string
  hasSucceedsSeparator: string
  hasTextAdmin: string
  hasTextAdminInvert: string
  hasTextCentered: string
  hasTextCenteredDesktop: string
  hasTextCenteredDesktopOnly: string
  hasTextCenteredFullhd: string
  hasTextCenteredMobile: string
  hasTextCenteredTablet: string
  hasTextCenteredTabletOnly: string
  hasTextCenteredTouch: string
  hasTextCenteredWidescreen: string
  hasTextCenteredWidescreenOnly: string
  hasTextCobalt: string
  hasTextCobaltInvert: string
  hasTextDanger: string
  hasTextDangerInvert: string
  hasTextDebug: string
  hasTextDebugInvert: string
  hasTextGrey: string
  hasTextGreyDark: string
  hasTextGreyLight: string
  hasTextGreyLighter: string
  hasTextInfo: string
  hasTextInfoInvert: string
  hasTextJustified: string
  hasTextJustifiedDesktop: string
  hasTextJustifiedDesktopOnly: string
  hasTextJustifiedFullhd: string
  hasTextJustifiedMobile: string
  hasTextJustifiedTablet: string
  hasTextJustifiedTabletOnly: string
  hasTextJustifiedTouch: string
  hasTextJustifiedWidescreen: string
  hasTextJustifiedWidescreenOnly: string
  hasTextLeft: string
  hasTextLeftDesktop: string
  hasTextLeftDesktopOnly: string
  hasTextLeftFullhd: string
  hasTextLeftMobile: string
  hasTextLeftTablet: string
  hasTextLeftTabletOnly: string
  hasTextLeftTouch: string
  hasTextLeftWidescreen: string
  hasTextLeftWidescreenOnly: string
  hasTextPrimary: string
  hasTextPrimaryInvert: string
  hasTextQuaternary: string
  hasTextQuaternaryInvert: string
  hasTextRight: string
  hasTextRightDesktop: string
  hasTextRightDesktopOnly: string
  hasTextRightFullhd: string
  hasTextRightMobile: string
  hasTextRightTablet: string
  hasTextRightTabletOnly: string
  hasTextRightTouch: string
  hasTextRightWidescreen: string
  hasTextRightWidescreenOnly: string
  hasTextSecondary: string
  hasTextSecondaryInvert: string
  hasTextSuccess: string
  hasTextSuccessInvert: string
  hasTextTertiary: string
  hasTextTertiaryDark: string
  hasTextTertiaryDarkInvert: string
  hasTextTertiaryInvert: string
  hasTextTertiaryLight: string
  hasTextTertiaryLightInvert: string
  hasTextWarning: string
  hasTextWarningInvert: string
  hasTextWeightBold: string
  hasTextWeightExtrabold: string
  hasTextWeightLight: string
  hasTextWeightMedium: string
  hasTextWeightNormal: string
  hasTextWeightSemibold: string
  hasTextWhite: string
  hasTextWhiteInvert: string
  hasVariant: string
  hasWireframes: string
  heading: string
  help: string
  hero: string
  heroBack: string
  heroBody: string
  heroButtons: string
  hoverColor: string
  icon: string
  iconAndText: string
  iconList: string
  image: string
  imageListItemImg: string
  imageListItemRoot: string
  imageListItemStandard: string
  imageListItemWoven: string
  imageListMasonry: string
  imageListRoot: string
  important: string
  input: string
  inputDynamicPlaceholder: string
  is_0: string
  is_0Desktop: string
  is_0DesktopOnly: string
  is_0Fullhd: string
  is_0Mobile: string
  is_0Tablet: string
  is_0TabletOnly: string
  is_0Touch: string
  is_0Widescreen: string
  is_0WidescreenOnly: string
  is_1: string
  is_10: string
  is_10Desktop: string
  is_10DesktopOnly: string
  is_10Fullhd: string
  is_10Mobile: string
  is_10Tablet: string
  is_10TabletOnly: string
  is_10Touch: string
  is_10Widescreen: string
  is_10WidescreenOnly: string
  is_11: string
  is_11Desktop: string
  is_11DesktopOnly: string
  is_11Fullhd: string
  is_11Mobile: string
  is_11Tablet: string
  is_11TabletOnly: string
  is_11Touch: string
  is_11Widescreen: string
  is_11WidescreenOnly: string
  is_12: string
  is_128x128: string
  is_12Desktop: string
  is_12DesktopOnly: string
  is_12Fullhd: string
  is_12Mobile: string
  is_12Tablet: string
  is_12TabletOnly: string
  is_12Touch: string
  is_12Widescreen: string
  is_12WidescreenOnly: string
  is_16x16: string
  is_1Desktop: string
  is_1DesktopOnly: string
  is_1Fullhd: string
  is_1Mobile: string
  is_1Tablet: string
  is_1TabletOnly: string
  is_1Touch: string
  is_1Widescreen: string
  is_1WidescreenOnly: string
  is_2: string
  is_24x24: string
  is_2Desktop: string
  is_2DesktopOnly: string
  is_2Fullhd: string
  is_2Mobile: string
  is_2Tablet: string
  is_2TabletOnly: string
  is_2Touch: string
  is_2Widescreen: string
  is_2WidescreenOnly: string
  is_3: string
  is_32x32: string
  is_3Desktop: string
  is_3DesktopOnly: string
  is_3Fullhd: string
  is_3Mobile: string
  is_3Tablet: string
  is_3TabletOnly: string
  is_3Touch: string
  is_3Widescreen: string
  is_3WidescreenOnly: string
  is_4: string
  is_48x48: string
  is_4Desktop: string
  is_4DesktopOnly: string
  is_4Fullhd: string
  is_4Mobile: string
  is_4Tablet: string
  is_4TabletOnly: string
  is_4Touch: string
  is_4Widescreen: string
  is_4WidescreenOnly: string
  is_5: string
  is_5Desktop: string
  is_5DesktopOnly: string
  is_5Fullhd: string
  is_5Mobile: string
  is_5Tablet: string
  is_5TabletOnly: string
  is_5Touch: string
  is_5Widescreen: string
  is_5WidescreenOnly: string
  is_6: string
  is_64x64: string
  is_6Desktop: string
  is_6DesktopOnly: string
  is_6Fullhd: string
  is_6Mobile: string
  is_6Tablet: string
  is_6TabletOnly: string
  is_6Touch: string
  is_6Widescreen: string
  is_6WidescreenOnly: string
  is_7: string
  is_7Desktop: string
  is_7DesktopOnly: string
  is_7Fullhd: string
  is_7Mobile: string
  is_7Tablet: string
  is_7TabletOnly: string
  is_7Touch: string
  is_7Widescreen: string
  is_7WidescreenOnly: string
  is_8: string
  is_8Desktop: string
  is_8DesktopOnly: string
  is_8Fullhd: string
  is_8Mobile: string
  is_8Tablet: string
  is_8TabletOnly: string
  is_8Touch: string
  is_8Widescreen: string
  is_8WidescreenOnly: string
  is_9: string
  is_96x96: string
  is_9Desktop: string
  is_9DesktopOnly: string
  is_9Fullhd: string
  is_9Mobile: string
  is_9Tablet: string
  is_9TabletOnly: string
  is_9Touch: string
  is_9Widescreen: string
  is_9WidescreenOnly: string
  isActive: string
  isAdmin: string
  isAlignContentBaseline: string
  isAlignContentCenter: string
  isAlignContentEnd: string
  isAlignContentFlexEnd: string
  isAlignContentFlexStart: string
  isAlignContentSpaceAround: string
  isAlignContentSpaceBetween: string
  isAlignContentSpaceEvenly: string
  isAlignContentStart: string
  isAlignContentStretch: string
  isAlignedEnd: string
  isAlignItemsBaseline: string
  isAlignItemsCenter: string
  isAlignItemsEnd: string
  isAlignItemsFlexEnd: string
  isAlignItemsFlexStart: string
  isAlignItemsSelfEnd: string
  isAlignItemsSelfStart: string
  isAlignItemsStart: string
  isAlignItemsStretch: string
  isAlignSelfAuto: string
  isAlignSelfBaseline: string
  isAlignSelfCenter: string
  isAlignSelfFlexEnd: string
  isAlignSelfFlexStart: string
  isAlignSelfStretch: string
  isAlternate: string
  isAncestor: string
  isAnimated: string
  isArrowEnd: string
  isArrowStart: string
  isBanner: string
  isBlock: string
  isBlockDesktop: string
  isBlockDesktopOnly: string
  isBlockFullhd: string
  isBlockMobile: string
  isBlockTablet: string
  isBlockTabletOnly: string
  isBlockTouch: string
  isBlockWidescreen: string
  isBlockWidescreenOnly: string
  isBodyHeader: string
  isBordered: string
  isBottom: string
  isBottomRight: string
  isBoxed: string
  isBrief: string
  isCapitalized: string
  isCentered: string
  isCenteredDesktop: string
  isCenteredMobile: string
  isCenteredTablet: string
  isCheckradio: string
  isChild: string
  isCircled: string
  isCircledAdmin: string
  isCircledCobalt: string
  isCircledDanger: string
  isCircledDebug: string
  isCircledGrey: string
  isCircledGreyDark: string
  isCircledGreyLight: string
  isCircledGreyLighter: string
  isCircledInfo: string
  isCircledPrimary: string
  isCircledQuaternary: string
  isCircledSecondary: string
  isCircledSuccess: string
  isCircledTertiary: string
  isCircledTertiaryDark: string
  isCircledTertiaryLight: string
  isCircledWarning: string
  isCircledWhite: string
  isClearfix: string
  isClipped: string
  isClippedToBottom: string
  isCobalt: string
  isCompact: string
  isComparative: string
  isCurrent: string
  isDanger: string
  isDebug: string
  isDescendant: string
  isDescriptive: string
  isDesktop: string
  isDisabled: string
  isDivider: string
  isDone: string
  isDownload: string
  isElastic: string
  isEmpty: string
  isExpandable: string
  isExpanded: string
  isExpansion: string
  isFirst: string
  isFixed: string
  isFlat: string
  isFlatPrimary: string
  isFlatQuaternary: string
  isFlatSecondary: string
  isFlatTertiary: string
  isFlex: string
  isFlexDesktop: string
  isFlexDesktopOnly: string
  isFlexDirectionColumn: string
  isFlexDirectionColumnReverse: string
  isFlexDirectionRow: string
  isFlexDirectionRowReverse: string
  isFlexFullhd: string
  isFlexGrow_0: string
  isFlexGrow_1: string
  isFlexGrow_2: string
  isFlexGrow_3: string
  isFlexGrow_4: string
  isFlexGrow_5: string
  isFlexible: string
  isFlexMobile: string
  isFlexShrink_0: string
  isFlexShrink_1: string
  isFlexShrink_2: string
  isFlexShrink_3: string
  isFlexShrink_4: string
  isFlexShrink_5: string
  isFlexTablet: string
  isFlexTabletOnly: string
  isFlexTouch: string
  isFlexWidescreen: string
  isFlexWidescreenOnly: string
  isFlexWrapNowrap: string
  isFlexWrapWrap: string
  isFlexWrapWrapReverse: string
  isFloating: string
  isFluid: string
  isFocused: string
  isFooterDesktop: string
  isFooterMobile: string
  isFooterSub: string
  isFourFifths: string
  isFourFifthsDesktop: string
  isFourFifthsFullhd: string
  isFourFifthsMobile: string
  isFourFifthsTablet: string
  isFourFifthsTouch: string
  isFourFifthsWidescreen: string
  isFourth: string
  isFull: string
  isFullDesktop: string
  isFullFullhd: string
  isFullhd: string
  isFullheight: string
  isFullMobile: string
  isFullTablet: string
  isFullTouch: string
  isFullWidescreen: string
  isFullwidth: string
  isFullwidthMobile: string
  isGap_1: string
  isGap_2: string
  isGap_3: string
  isGap_4: string
  isGap_5: string
  isGap_6: string
  isGap_7: string
  isGapless: string
  isGrey: string
  isGreyDark: string
  isGreyLight: string
  isGreyLighter: string
  isGrouped: string
  isGroupedCentered: string
  isGroupedMultiline: string
  isGroupedRight: string
  isHalf: string
  isHalfDesktop: string
  isHalfFullhd: string
  isHalfMobile: string
  isHalfTablet: string
  isHalfTouch: string
  isHalfWidescreen: string
  isHat: string
  isHidden: string
  isHiddenDesktop: string
  isHiddenDesktopOnly: string
  isHiddenFullhd: string
  isHiddenMobile: string
  isHiddenTablet: string
  isHiddenTabletOnly: string
  isHiddenTouch: string
  isHiddenWidescreen: string
  isHiddenWidescreenOnly: string
  isHighlighted: string
  isHorizontal: string
  isHoverable: string
  isHovered: string
  isHuge: string
  isIcon: string
  isIllustratedMobile: string
  isImage: string
  isIncluded: string
  isInfo: string
  isInline: string
  isInlineBlock: string
  isInlineBlockDesktop: string
  isInlineBlockDesktopOnly: string
  isInlineBlockFullhd: string
  isInlineBlockMobile: string
  isInlineBlockTablet: string
  isInlineBlockTabletOnly: string
  isInlineBlockTouch: string
  isInlineBlockWidescreen: string
  isInlineBlockWidescreenOnly: string
  isInlined: string
  isInlineDesktop: string
  isInlineDesktopOnly: string
  isInlineFlex: string
  isInlineFlexDesktop: string
  isInlineFlexDesktopOnly: string
  isInlineFlexFullhd: string
  isInlineFlexMobile: string
  isInlineFlexTablet: string
  isInlineFlexTabletOnly: string
  isInlineFlexTouch: string
  isInlineFlexWidescreen: string
  isInlineFlexWidescreenOnly: string
  isInlineFullhd: string
  isInlineMobile: string
  isInlineTablet: string
  isInlineTabletOnly: string
  isInlineTouch: string
  isInlineWidescreen: string
  isInlineWidescreenOnly: string
  isInstit: string
  isInverted: string
  isInvertedMobile: string
  isInvisible: string
  isInvisibleDesktop: string
  isInvisibleDesktopOnly: string
  isInvisibleFullhd: string
  isInvisibleMobile: string
  isInvisibleTablet: string
  isInvisibleTabletOnly: string
  isInvisibleTouch: string
  isInvisibleWidescreen: string
  isInvisibleWidescreenOnly: string
  isItalic: string
  isJustifiedCenter: string
  isJustifiedCenterDesktop: string
  isJustifiedCenterDesktopOnly: string
  isJustifiedCenterFullhd: string
  isJustifiedCenterMobile: string
  isJustifiedCenterTablet: string
  isJustifiedCenterTabletOnly: string
  isJustifiedCenterTouch: string
  isJustifiedCenterWidescreen: string
  isJustifiedCenterWidescreenOnly: string
  isJustifiedEnd: string
  isJustifiedEndDesktop: string
  isJustifiedEndDesktopOnly: string
  isJustifiedEndFullhd: string
  isJustifiedEndMobile: string
  isJustifiedEndTablet: string
  isJustifiedEndTabletOnly: string
  isJustifiedEndTouch: string
  isJustifiedEndWidescreen: string
  isJustifiedEndWidescreenOnly: string
  isJustifiedStart: string
  isJustifiedStartDesktop: string
  isJustifiedStartDesktopOnly: string
  isJustifiedStartFullhd: string
  isJustifiedStartMobile: string
  isJustifiedStartTablet: string
  isJustifiedStartTabletOnly: string
  isJustifiedStartTouch: string
  isJustifiedStartWidescreen: string
  isJustifiedStartWidescreenOnly: string
  isJustifyContentCenter: string
  isJustifyContentEnd: string
  isJustifyContentFlexEnd: string
  isJustifyContentFlexStart: string
  isJustifyContentLeft: string
  isJustifyContentRight: string
  isJustifyContentSpaceAround: string
  isJustifyContentSpaceBetween: string
  isJustifyContentSpaceEvenly: string
  isJustifyContentStart: string
  isLarge: string
  isLeft: string
  isLevel: string
  isLoaded: string
  isLoading: string
  isLong: string
  isLowercase: string
  isMainPrice: string
  isMarginless: string
  isMaxDesktop: string
  isMaxWidescreen: string
  isMe: string
  isMedium: string
  isMegadropdownParent: string
  isMobile: string
  isMotionlessDesktop: string
  isMultiline: string
  isMultiple: string
  isMutuallyExclusive: string
  isNarrow: string
  isNarrowDesktop: string
  isNarrowFullhd: string
  isNarrowMobile: string
  isNarrowTablet: string
  isNarrowTouch: string
  isNarrowWidescreen: string
  isNew: string
  isNormal: string
  isNowrap: string
  isNpm: string
  isOffset_1: string
  isOffset_10: string
  isOffset_10Desktop: string
  isOffset_10Fullhd: string
  isOffset_10Mobile: string
  isOffset_10Tablet: string
  isOffset_10Touch: string
  isOffset_10Widescreen: string
  isOffset_11: string
  isOffset_11Desktop: string
  isOffset_11Fullhd: string
  isOffset_11Mobile: string
  isOffset_11Tablet: string
  isOffset_11Touch: string
  isOffset_11Widescreen: string
  isOffset_12: string
  isOffset_12Desktop: string
  isOffset_12Fullhd: string
  isOffset_12Mobile: string
  isOffset_12Tablet: string
  isOffset_12Touch: string
  isOffset_12Widescreen: string
  isOffset_1Desktop: string
  isOffset_1Fullhd: string
  isOffset_1Mobile: string
  isOffset_1Tablet: string
  isOffset_1Touch: string
  isOffset_1Widescreen: string
  isOffset_2: string
  isOffset_2Desktop: string
  isOffset_2Fullhd: string
  isOffset_2Mobile: string
  isOffset_2Tablet: string
  isOffset_2Touch: string
  isOffset_2Widescreen: string
  isOffset_3: string
  isOffset_3Desktop: string
  isOffset_3Fullhd: string
  isOffset_3Mobile: string
  isOffset_3Tablet: string
  isOffset_3Touch: string
  isOffset_3Widescreen: string
  isOffset_4: string
  isOffset_4Desktop: string
  isOffset_4Fullhd: string
  isOffset_4Mobile: string
  isOffset_4Tablet: string
  isOffset_4Touch: string
  isOffset_4Widescreen: string
  isOffset_5: string
  isOffset_5Desktop: string
  isOffset_5Fullhd: string
  isOffset_5Mobile: string
  isOffset_5Tablet: string
  isOffset_5Touch: string
  isOffset_5Widescreen: string
  isOffset_6: string
  isOffset_6Desktop: string
  isOffset_6Fullhd: string
  isOffset_6Mobile: string
  isOffset_6Tablet: string
  isOffset_6Touch: string
  isOffset_6Widescreen: string
  isOffset_7: string
  isOffset_7Desktop: string
  isOffset_7Fullhd: string
  isOffset_7Mobile: string
  isOffset_7Tablet: string
  isOffset_7Touch: string
  isOffset_7Widescreen: string
  isOffset_8: string
  isOffset_8Desktop: string
  isOffset_8Fullhd: string
  isOffset_8Mobile: string
  isOffset_8Tablet: string
  isOffset_8Touch: string
  isOffset_8Widescreen: string
  isOffset_9: string
  isOffset_9Desktop: string
  isOffset_9Fullhd: string
  isOffset_9Mobile: string
  isOffset_9Tablet: string
  isOffset_9Touch: string
  isOffset_9Widescreen: string
  isOffsetFourFifths: string
  isOffsetFourFifthsDesktop: string
  isOffsetFourFifthsFullhd: string
  isOffsetFourFifthsMobile: string
  isOffsetFourFifthsTablet: string
  isOffsetFourFifthsTouch: string
  isOffsetFourFifthsWidescreen: string
  isOffsetHalf: string
  isOffsetHalfDesktop: string
  isOffsetHalfFullhd: string
  isOffsetHalfMobile: string
  isOffsetHalfTablet: string
  isOffsetHalfTouch: string
  isOffsetHalfWidescreen: string
  isOffsetOneFifth: string
  isOffsetOneFifthDesktop: string
  isOffsetOneFifthFullhd: string
  isOffsetOneFifthMobile: string
  isOffsetOneFifthTablet: string
  isOffsetOneFifthTouch: string
  isOffsetOneFifthWidescreen: string
  isOffsetOneQuarter: string
  isOffsetOneQuarterDesktop: string
  isOffsetOneQuarterFullhd: string
  isOffsetOneQuarterMobile: string
  isOffsetOneQuarterTablet: string
  isOffsetOneQuarterTouch: string
  isOffsetOneQuarterWidescreen: string
  isOffsetOneThird: string
  isOffsetOneThirdDesktop: string
  isOffsetOneThirdFullhd: string
  isOffsetOneThirdMobile: string
  isOffsetOneThirdTablet: string
  isOffsetOneThirdTouch: string
  isOffsetOneThirdWidescreen: string
  isOffsetThreeFifths: string
  isOffsetThreeFifthsDesktop: string
  isOffsetThreeFifthsFullhd: string
  isOffsetThreeFifthsMobile: string
  isOffsetThreeFifthsTablet: string
  isOffsetThreeFifthsTouch: string
  isOffsetThreeFifthsWidescreen: string
  isOffsetThreeQuarters: string
  isOffsetThreeQuartersDesktop: string
  isOffsetThreeQuartersFullhd: string
  isOffsetThreeQuartersMobile: string
  isOffsetThreeQuartersTablet: string
  isOffsetThreeQuartersTouch: string
  isOffsetThreeQuartersWidescreen: string
  isOffsetTwoFifths: string
  isOffsetTwoFifthsDesktop: string
  isOffsetTwoFifthsFullhd: string
  isOffsetTwoFifthsMobile: string
  isOffsetTwoFifthsTablet: string
  isOffsetTwoFifthsTouch: string
  isOffsetTwoFifthsWidescreen: string
  isOffsetTwoThirds: string
  isOffsetTwoThirdsDesktop: string
  isOffsetTwoThirdsFullhd: string
  isOffsetTwoThirdsMobile: string
  isOffsetTwoThirdsTablet: string
  isOffsetTwoThirdsTouch: string
  isOffsetTwoThirdsWidescreen: string
  isOneFifth: string
  isOneFifthDesktop: string
  isOneFifthFullhd: string
  isOneFifthMobile: string
  isOneFifthTablet: string
  isOneFifthTouch: string
  isOneFifthWidescreen: string
  isOneQuarter: string
  isOneQuarterDesktop: string
  isOneQuarterFullhd: string
  isOneQuarterMobile: string
  isOneQuarterTablet: string
  isOneQuarterTouch: string
  isOneQuarterWidescreen: string
  isOneThird: string
  isOneThirdDesktop: string
  isOneThirdFullhd: string
  isOneThirdMobile: string
  isOneThirdTablet: string
  isOneThirdTouch: string
  isOneThirdWidescreen: string
  isOutlined: string
  isOverlapped: string
  isOverlay: string
  isPaddingless: string
  isParent: string
  isPartner: string
  isPlain: string
  isPolyfilled: string
  isPopoverActive: string
  isPopoverBottom: string
  isPopoverLeft: string
  isPopoverRight: string
  isPrimary: string
  isPulledLeft: string
  isPulledRight: string
  isQuaternary: string
  isRadiusless: string
  isReversed: string
  isRight: string
  isRightAligned: string
  isRounded: string
  isRtl: string
  isScrollable: string
  isSearching: string
  isSecond: string
  isSecondary: string
  isSectionTitle: string
  isSelected: string
  isSelectLine: string
  isShadowless: string
  isShort: string
  isSidebarMenu: string
  isSize_1: string
  isSize_1Desktop: string
  isSize_1Fullhd: string
  isSize_1Mobile: string
  isSize_1Tablet: string
  isSize_1Touch: string
  isSize_1Widescreen: string
  isSize_2: string
  isSize_2Desktop: string
  isSize_2Fullhd: string
  isSize_2Mobile: string
  isSize_2Tablet: string
  isSize_2Touch: string
  isSize_2Widescreen: string
  isSize_3: string
  isSize_3Desktop: string
  isSize_3Fullhd: string
  isSize_3Mobile: string
  isSize_3Tablet: string
  isSize_3Touch: string
  isSize_3Widescreen: string
  isSize_4: string
  isSize_4Desktop: string
  isSize_4Fullhd: string
  isSize_4Mobile: string
  isSize_4Tablet: string
  isSize_4Touch: string
  isSize_4Widescreen: string
  isSize_5: string
  isSize_5Desktop: string
  isSize_5Fullhd: string
  isSize_5Mobile: string
  isSize_5Tablet: string
  isSize_5Touch: string
  isSize_5Widescreen: string
  isSize_6: string
  isSize_6Desktop: string
  isSize_6Fullhd: string
  isSize_6Mobile: string
  isSize_6Tablet: string
  isSize_6Touch: string
  isSize_6Widescreen: string
  isSize_7: string
  isSize_7Desktop: string
  isSize_7Fullhd: string
  isSize_7Mobile: string
  isSize_7Tablet: string
  isSize_7Touch: string
  isSize_7Widescreen: string
  isSize_8: string
  isSize_8Desktop: string
  isSize_8Fullhd: string
  isSize_8Mobile: string
  isSize_8Tablet: string
  isSize_8Touch: string
  isSize_8Widescreen: string
  isSmall: string
  isSmallMobile: string
  isSpaced: string
  isSpecial: string
  isStacked: string
  isStackedDesktop: string
  isStackedMobile: string
  isStackedTablet: string
  isStackedWidescreen: string
  isStatic: string
  isSticky: string
  isStretched: string
  isStriked: string
  isStriped: string
  isStrong: string
  isSuccess: string
  isSwitch: string
  isTertiary: string
  isTertiaryDark: string
  isTertiaryLight: string
  isText: string
  isThreeFifths: string
  isThreeFifthsDesktop: string
  isThreeFifthsFullhd: string
  isThreeFifthsMobile: string
  isThreeFifthsTablet: string
  isThreeFifthsTouch: string
  isThreeFifthsWidescreen: string
  isThreeQuarters: string
  isThreeQuartersDesktop: string
  isThreeQuartersFullhd: string
  isThreeQuartersMobile: string
  isThreeQuartersTablet: string
  isThreeQuartersTouch: string
  isThreeQuartersWidescreen: string
  isTooltipActive: string
  isTop: string
  isTransparent: string
  isTransparentOnly: string
  isTwoFifths: string
  isTwoFifthsDesktop: string
  isTwoFifthsFullhd: string
  isTwoFifthsMobile: string
  isTwoFifthsTablet: string
  isTwoFifthsTouch: string
  isTwoFifthsWidescreen: string
  isTwoThirds: string
  isTwoThirdsDesktop: string
  isTwoThirdsFullhd: string
  isTwoThirdsMobile: string
  isTwoThirdsTablet: string
  isTwoThirdsTouch: string
  isTwoThirdsWidescreen: string
  isUnavailable: string
  isUnboxed: string
  isUnderline: string
  isUnselectable: string
  isUp: string
  isUppercase: string
  isVariable: string
  isVcentered: string
  isVcenteredDesktop: string
  isVcenteredMobile: string
  isVcenteredTablet: string
  isVertical: string
  isVerticalMobile: string
  isVeryLong: string
  isVeryShort: string
  isVolumeControl: string
  isWaiting: string
  isWarning: string
  isWhite: string
  isWidescreen: string
  isWireframe: string
  isWrapped: string
  knob: string
  label: string
  level: string
  levelItem: string
  levelLeft: string
  levelRight: string
  link: string
  loader: string
  loadingPulse: string
  login: string
  logo: string
  main: string
  mainContent: string
  media: string
  mention: string
  menu: string
  menuClose: string
  menuLabel: string
  menuList: string
  menuOpen: string
  menuTitle: string
  modal: string
  modalBackground: string
  modalClose: string
  modalContent: string
  modalTitle: string
  navbar: string
  navbarBrand: string
  navbarCategoryTitle: string
  navbarDivider: string
  navbarDropdown: string
  navbarDropdownClose: string
  navbarDropdownSection: string
  navbarEnd: string
  navbarExtras: string
  navbarHeader: string
  navbarIcons: string
  navbarItem: string
  navbarItemAccordion: string
  navbarItemAccordionBack: string
  navbarItemAccordionContent: string
  navbarItemAccordionHeader: string
  navbarItemAccordionTitle: string
  navbarLink: string
  navbarLinks: string
  navbarMenu: string
  navbarStart: string
  navbarTitle: string
  none: string
  notification: string
  notifications: string
  number: string
  options: string
  pagination: string
  paginationEllipsis: string
  paginationLink: string
  paginationList: string
  paginationNext: string
  paginationPrevious: string
  paragraph: string
  partnersIcons: string
  patternDark: string
  period: string
  periode: string
  pie: string
  placeHolderShimmer: string
  planCallToAction: string
  planFooter: string
  planHeader: string
  planItem: string
  planItemDetails: string
  planItems: string
  planItemTitle: string
  planPrice: string
  planSticker: string
  plusSymbol: string
  popover: string
  popoverContent: string
  popoverTrigger: string
  price: string
  priceDetails: string
  pricingPlan: string
  pricingPlanExtra: string
  pricingPlanProduct: string
  pricingTable: string
  pricingTableExtra: string
  productTour: string
  productTourTargetActive: string
  progress: string
  progress_0: string
  progress_1: string
  progress_10: string
  progress_100: string
  progress_11: string
  progress_12: string
  progress_13: string
  progress_14: string
  progress_15: string
  progress_16: string
  progress_17: string
  progress_18: string
  progress_19: string
  progress_2: string
  progress_20: string
  progress_21: string
  progress_22: string
  progress_23: string
  progress_24: string
  progress_25: string
  progress_26: string
  progress_27: string
  progress_28: string
  progress_29: string
  progress_3: string
  progress_30: string
  progress_31: string
  progress_32: string
  progress_33: string
  progress_34: string
  progress_35: string
  progress_36: string
  progress_37: string
  progress_38: string
  progress_39: string
  progress_4: string
  progress_40: string
  progress_41: string
  progress_42: string
  progress_43: string
  progress_44: string
  progress_45: string
  progress_46: string
  progress_47: string
  progress_48: string
  progress_49: string
  progress_5: string
  progress_50: string
  progress_51: string
  progress_52: string
  progress_53: string
  progress_54: string
  progress_55: string
  progress_56: string
  progress_57: string
  progress_58: string
  progress_59: string
  progress_6: string
  progress_60: string
  progress_61: string
  progress_62: string
  progress_63: string
  progress_64: string
  progress_65: string
  progress_66: string
  progress_67: string
  progress_68: string
  progress_69: string
  progress_7: string
  progress_70: string
  progress_71: string
  progress_72: string
  progress_73: string
  progress_74: string
  progress_75: string
  progress_76: string
  progress_77: string
  progress_78: string
  progress_79: string
  progress_8: string
  progress_80: string
  progress_81: string
  progress_82: string
  progress_83: string
  progress_84: string
  progress_85: string
  progress_86: string
  progress_87: string
  progress_88: string
  progress_89: string
  progress_9: string
  progress_90: string
  progress_91: string
  progress_92: string
  progress_93: string
  progress_94: string
  progress_95: string
  progress_96: string
  progress_97: string
  progress_98: string
  progress_99: string
  progressBar: string
  progressCircle: string
  progressCircleBackgroundEmpty: string
  progressCircleBackgroundSecondary: string
  progressCircleBackgroundTertiary: string
  progressCircleBackgroundWarning: string
  progressCircleContent: string
  progressCircleSlice: string
  progressCircleSub: string
  progressCircleTitle: string
  radialProgressBar: string
  radialProgressBars: string
  reactAutosuggestContainer: string
  row: string
  rows: string
  searchAutocomplete: string
  searchAutosuggest: string
  searchBar: string
  searchModal: string
  searchNoModal: string
  searchResults: string
  section: string
  select: string
  showMore: string
  slice: string
  sliceBody: string
  sliceCallToAction: string
  sliceContent: string
  sliceGroup: string
  sliceIcon: string
  sliceImage: string
  slices: string
  sliceSelect: string
  sliderDot: string
  slidingLink: string
  small: string
  socialIcons: string
  specification: string
  spinAround: string
  step: string
  stepper: string
  sticker: string
  subFooter: string
  subfooterLink: string
  subfooterTitle: string
  subtable: string
  subtitle: string
  suptitle: string
  table: string
  tableContainer: string
  tabs: string
  tag: string
  tags: string
  text: string
  textarea: string
  tile: string
  tilesContainer: string
  timeline: string
  timelineContent: string
  timelineHeader: string
  timelineItem: string
  timelineMarker: string
  title: string
  toggle: string
  toolbar: string
  toolbarGroup: string
  toolbarItem: string
  toolbarRow: string
  toolbarSpace: string
  tooltip: string
  user: string
  userMenu: string
  value: string
  wave: string
  withArrow: string
  wrapper: string
}

export type ClassNames = keyof Styles

declare const styles: Styles

export default styles
