export type Styles = {
  accordion: string
  accordionContent: string
  accordionHeader: string
  accordions: string
  badge: string
  bellbounce: string
  bellring: string
  bgConnected: string
  box: string
  boxContent: string
  boxFooter: string
  boxHeader: string
  burgerMenu: string
  button: string
  buttons: string
  bytelFooter: string
  column: string
  columns: string
  container: string
  control: string
  details: string
  dl: string
  fa: string
  field: string
  fieldBody: string
  fieldLabel: string
  file: string
  fileCta: string
  fileIcon: string
  fileInput: string
  fileLabel: string
  fileName: string
  flexi4G: string
  flexi4G4Gplus: string
  flexi4G5G: string
  flexi4G5GPlus: string
  flexi4GPlus: string
  flexi5G: string
  flexiAccessibility: string
  flexiAccomodation: string
  flexiAddcalendarRdv: string
  flexiAdvisor: string
  flexiAfrica: string
  flexiAirTravel: string
  flexiArchiving: string
  flexiArtificialIntelligence: string
  flexiArtistChair: string
  flexiAt: string
  flexiAtCheckS: string
  flexiAtCogsCircle: string
  flexiAtExclamationCircle: string
  flexiAtGlobe: string
  flexiAtInfinityCircle: string
  flexiAtInfo: string
  flexiAtPlusCircle: string
  flexiAtUnavailable: string
  flexiAudioVisual: string
  flexiAutoplan: string
  flexiBabyphone: string
  flexiBadges: string
  flexiBall: string
  flexiBank: string
  flexiBarcodeSearch: string
  flexiBattery: string
  flexiBduo: string
  flexiBeautician: string
  flexiBellRinging: string
  flexiBluetooth: string
  flexiBox: string
  flexiBox4G: string
  flexiBoxAdd: string
  flexiBoxCheckCircle: string
  flexiBoxCheckCircleS: string
  flexiBoxEole: string
  flexiBoxExclamationCircle: string
  flexiBoxFaq: string
  flexiBoxInfoCircle: string
  flexiBoxInfoCogs: string
  flexiBoxMobile: string
  flexiBoxRedo: string
  flexiBoxSmartTv: string
  flexiBoxStethoscope: string
  flexiBoxUnavailable: string
  flexiBtv: string
  flexiBtvIllimite: string
  flexiBtvplus: string
  flexiBusinessTrip: string
  flexiCalendar: string
  flexiCalendarClockCircle: string
  flexiCalendarCogsCircle: string
  flexiCalendarExclamationCircle: string
  flexiCalendarInfoCircle: string
  flexiCalendarPlusCircle: string
  flexiCalendarQuestionCircle: string
  flexiCalendarUnavailable: string
  flexiCamera: string
  flexiCarPark: string
  flexiCarpooling: string
  flexiCarRent: string
  flexiCatering: string
  flexiCheck: string
  flexiCheckCircle: string
  flexiChildrenAccess: string
  flexiChip: string
  flexiClapperboard: string
  flexiCleanSurface: string
  flexiClickCollect2H: string
  flexiClipboardChecklist: string
  flexiClosed: string
  flexiCloud: string
  flexiCloud100Go: string
  flexiCloud20Go: string
  flexiCloud30Go: string
  flexiCloud50Go: string
  flexiCloud70Go: string
  flexiCloudCheck: string
  flexiCloudCheckS: string
  flexiCloudCogsCircle: string
  flexiCloudExclamationCircle: string
  flexiCloudGlobe: string
  flexiCloudInfinity: string
  flexiCloudPlusCircle: string
  flexiCloudSave: string
  flexiCo2Emission: string
  flexiCogs: string
  flexiCollaborativeLibrary: string
  flexiComment: string
  flexiCommentEarth: string
  flexiCommentExclamationCircle: string
  flexiCommentEye: string
  flexiCommentQuestion: string
  flexiCommentsQuestionDots: string
  flexiCommentVoicemail: string
  flexiCommunity: string
  flexiConcierge: string
  flexiContact: string
  flexiContactlessPayment: string
  flexiCorporateCard: string
  flexiCourier: string
  flexiCreditCard: string
  flexiCreditCardAccepted: string
  flexiCreditCardLock: string
  flexiCreditCards: string
  flexiCreditCards12: string
  flexiCripplingDisease: string
  flexiCse: string
  flexiDesktop: string
  flexiDiagnostic: string
  flexiDistance: string
  flexiDontTouch: string
  flexiDuplicata: string
  flexiEarSlash: string
  flexiEarth: string
  flexiEcoConception: string
  flexiEcommerceProductReturn: string
  flexiEcommercePromoLabel: string
  flexiEcoresponsibleDigital: string
  flexiElectricalOverload: string
  flexiElectricalPlug: string
  flexiElectricCar: string
  flexiEnergy: string
  flexiEnergyOptimization: string
  flexiEnvelope: string
  flexiEnvelopePlusCircle: string
  flexiEnvironmentalFootprint: string
  flexiEsim: string
  flexiEthics: string
  flexiEurope: string
  flexiEuros: string
  flexiExclamation: string
  flexiExclamationCircle: string
  flexiExclamationRedo: string
  flexiExclamationTriangle: string
  flexiFacemask1: string
  flexiFacemask2: string
  flexiFaciliti: string
  flexiFileAttached: string
  flexiFileEuro: string
  flexiFileEuroCheckCircle: string
  flexiFileEuroCheckCircleS: string
  flexiFileEuroExclamationCircle: string
  flexiFileEuroInfoCircle: string
  flexiFileEuroLockCircle: string
  flexiFileEuroQuestionCircle: string
  flexiFileList: string
  flexiFileManagement: string
  flexiFileNew: string
  flexiFilePdf: string
  flexiFilm: string
  flexiFingerprint: string
  flexiFirstRuralArea: string
  flexiFlashSell: string
  flexiFlexymoovBicycle: string
  flexiFlowerOrder: string
  flexiFrance: string
  flexiFranceMarker: string
  flexiFrown: string
  flexiGamepad: string
  flexiGamesConsole: string
  flexiGauge: string
  flexiGaugeCogsCircle: string
  flexiGaugeExclamationCircle: string
  flexiGaugePlusCircle: string
  flexiGift: string
  flexiGoodPractices: string
  flexiHairdresser: string
  flexiHandicapzero: string
  flexiHandMobile: string
  flexiHandsfree: string
  flexiHandsHelping: string
  flexiHandTools: string
  flexiHeadphones: string
  flexiHeart: string
  flexiHome: string
  flexiHomeTools: string
  flexiHotspot: string
  flexiHourglass: string
  flexiHydroGel: string
  flexiIdentity: string
  flexiImmersiveContentGlass: string
  flexiImmersiveContentPeople: string
  flexiInternalFraud: string
  flexiIot: string
  flexiIp: string
  flexiLaFibre: string
  flexiLaptop: string
  flexiLaptopTabletMobile: string
  flexiLightbulbOn: string
  flexiLinesSpeed: string
  flexiLink: string
  flexiLinkCopy: string
  flexiLock: string
  flexiMail: string
  flexiMailboxMarker: string
  flexiMaker: string
  flexiMapMarker: string
  flexiMarker: string
  flexiMassage: string
  flexiMentalDisability: string
  flexiMentalHandicap: string
  flexiMicrowaves: string
  flexiMobile: string
  flexiMobile06Slash: string
  flexiMobile07Slash: string
  flexiMobile08Slash: string
  flexiMobileBan: string
  flexiMobileBroken: string
  flexiMobileCloud: string
  flexiMobileComment: string
  flexiMobileEuro: string
  flexiMobileEye: string
  flexiMobileGlobe: string
  flexiMobileHand: string
  flexiMobileInfinity: string
  flexiMobileLock: string
  flexiMobilePercentage: string
  flexiMobilePlusSimCards: string
  flexiMobileReconditioned: string
  flexiMobileRecovery: string
  flexiMobileSync: string
  flexiMobileTools: string
  flexiMobileUpDown: string
  flexiModem3G: string
  flexiMotivation: string
  flexiMouse: string
  flexiMovingPersonsGoods: string
  flexinessRoot: string
  flexiNetwork: string
  flexiNetworkAntenna: string
  flexiNewspapers: string
  flexiNotebookTarifs: string
  flexiNotes: string
  flexiNotificationBottom: string
  flexiNotificationTop: string
  flexiOfficeSupply: string
  flexiOptician: string
  flexiPackagePreparation: string
  flexiPaperclip: string
  flexiParcel: string
  flexiPause: string
  flexiPaymentAmericanexpress: string
  flexiPaymentCb: string
  flexiPaymentMastercard: string
  flexiPaymentPaypal: string
  flexiPaymentVisa: string
  flexiPersonDoor: string
  flexiPhone: string
  flexiPhoneAfrica: string
  flexiPhoneBurger: string
  flexiPhoneEuro: string
  flexiPhoneEurope: string
  flexiPhoneGlobe: string
  flexiPhoneIncomingCall: string
  flexiPhoneInfinity: string
  flexiPhoneNotes: string
  flexiPhoneOutgoingCall: string
  flexiPhonePlusSimCard: string
  flexiPhoneSwitzerland: string
  flexiPhysicalDisability: string
  flexiPlayBeginning: string
  flexiPlayCircle: string
  flexiPlexiExchange: string
  flexiPlugCheck: string
  flexiPlus: string
  flexiPlusCircle: string
  flexiPrinter: string
  flexiPrintingStationery: string
  flexiPriorityPath: string
  flexiRecycle: string
  flexiRedo: string
  flexiRedo14Days: string
  flexiRedo30Days: string
  flexiRedo7Days: string
  flexiReduceCo2Emission: string
  flexiRemote: string
  flexiRepeater: string
  flexiRepeaterAlt: string
  flexiRestrictedArea: string
  flexiRingtoneWelcomeSound: string
  flexiRotation360: string
  flexiRules: string
  flexiSamples: string
  flexiSamplesCogsCircle: string
  flexiSamplesExclamationMarkCircle: string
  flexiSamplesPlusCircle: string
  flexiSatelliteAntenna: string
  flexiScan: string
  flexiSdCard: string
  flexiSearch: string
  flexiSecurityHealth: string
  flexiShield: string
  flexiShieldAt: string
  flexiShieldCheck: string
  flexiShieldExclamation: string
  flexiShieldPrivateLife: string
  flexiShootingStar: string
  flexiShoppingBag: string
  flexiSimCard: string
  flexiSimCardRedo: string
  flexiSimCards: string
  flexiSimCardUnlock: string
  flexiSmile: string
  flexiSmileNocircled: string
  flexiSmilePlus: string
  flexiSmsInfo: string
  flexiSocialFacebook: string
  flexiSocialInstagram: string
  flexiSocialTwitter: string
  flexiSocialYoutube: string
  flexiSports: string
  flexiSteeringWheel: string
  flexiStopwatch: string
  flexiStopwatch2H: string
  flexiStopwatchClickCollect: string
  flexiStopwatchClickCollect2H: string
  flexiStore: string
  flexiStoreLocator: string
  flexiSunEuro: string
  flexiSustainableDevelopment: string
  flexiSync: string
  flexiTablet: string
  flexiTeamMeal: string
  flexiTh: string
  flexiThunderRedo: string
  flexiTimes: string
  flexiTimesCircle: string
  flexiTools: string
  flexiTopNews: string
  flexiTrainingDiploma: string
  flexiTransport: string
  flexiTrash: string
  flexiTravelAgency: string
  flexiTravelPolicies: string
  flexiTruck: string
  flexiTruckSpeed: string
  flexiTurkey: string
  flexiTv: string
  flexiTv4K: string
  flexiTv8K: string
  flexiTvBtv: string
  flexiTvCurved: string
  flexiTvHd: string
  flexiTvInfinity: string
  flexiTvMulti: string
  flexiTvMultiOpticalFiber: string
  flexiTvVod: string
  flexiUiArrowDown: string
  flexiUiArrowDownR: string
  flexiUiArrowLeft: string
  flexiUiArrowLeftR: string
  flexiUiArrowRight: string
  flexiUiArrowRightR: string
  flexiUiArrowUp: string
  flexiUiArrowUpR: string
  flexiUiBell: string
  flexiUiCheck: string
  flexiUiCheckCircle: string
  flexiUiCheckCircleS: string
  flexiUiCheckR: string
  flexiUiDownload: string
  flexiUiEnvelope: string
  flexiUiExclamation: string
  flexiUiExclamationCircle: string
  flexiUiExclamationCircleS: string
  flexiUiExclamationR: string
  flexiUiEye: string
  flexiUiEyeS: string
  flexiUiEyeSlash: string
  flexiUiEyeSlashS: string
  flexiUiHome: string
  flexiUiInfo: string
  flexiUiInfoCircle: string
  flexiUiInfoCircleR: string
  flexiUiLogo: string
  flexiUiMarker: string
  flexiUiMarkerS: string
  flexiUiMenu: string
  flexiUiMinus: string
  flexiUiMinusCircle: string
  flexiUiPauseS: string
  flexiUiPencil: string
  flexiUiPencilS: string
  flexiUiPlayS: string
  flexiUiPlus: string
  flexiUiPlusCircle: string
  flexiUiPlusCircleR: string
  flexiUiPlusCircleS: string
  flexiUiPlusR: string
  flexiUiPower: string
  flexiUiQuestion: string
  flexiUiQuestionCircle: string
  flexiUiQuestionCircleR: string
  flexiUiRelaisColisExpress: string
  flexiUiSearch: string
  flexiUiSearchR: string
  flexiUiShoppingBag: string
  flexiUiShoppingCart: string
  flexiUiSliders: string
  flexiUiStar: string
  flexiUiStarHalf: string
  flexiUiStarS: string
  flexiUiTimes: string
  flexiUiTimesCircle: string
  flexiUiTimesCircleR: string
  flexiUiTimesCircleS: string
  flexiUiTimesR: string
  flexiUiTrash: string
  flexiUiTrashS: string
  flexiUiUpload: string
  flexiUiUser: string
  flexiUnavailable: string
  flexiUnlimited: string
  flexiUsbkey: string
  flexiUser: string
  flexiUserHeadset: string
  flexiUsers: string
  flexiUsersShieldS: string
  flexiUsersShieldStarS: string
  flexiUserTie: string
  flexiVictory: string
  flexiVisor: string
  flexiVisuallyImpaired: string
  flexiVoiceAssistance: string
  flexiVoicemail: string
  flexiVolumeOff: string
  flexiVolumeOn: string
  flexiVSign: string
  flexiVtcTaxiMotorbike: string
  flexiWall: string
  flexiWasteReduction: string
  flexiWatch: string
  flexiWebcam: string
  flexiWifi: string
  flexiWifiLow: string
  flexiWifiMedium: string
  flexiWindow: string
  flexiWorkplaceLayout: string
  flexiWorkshop: string
  footer: string
  hasAddons: string
  hasAddonsCentered: string
  hasAddonsFullwidth: string
  hasAddonsRight: string
  hasBackground: string
  hasBackgroundAdmin: string
  hasBackgroundCobalt: string
  hasBackgroundDanger: string
  hasBackgroundDebug: string
  hasBackgroundGrey: string
  hasBackgroundGreyDark: string
  hasBackgroundGreyLight: string
  hasBackgroundGreyLighter: string
  hasBackgroundInfo: string
  hasBackgroundPrimary: string
  hasBackgroundQuaternary: string
  hasBackgroundSecondary: string
  hasBackgroundSuccess: string
  hasBackgroundTertiary: string
  hasBackgroundWarning: string
  hasBackgroundWhite: string
  hasBorderRadius: string
  hasBorderRadiusLarge: string
  hasBorderRadiusSmall: string
  hasDropdownArrow: string
  hasDynamicPlaceholder: string
  hasEndingArrow: string
  hasHat: string
  hasIcon: string
  hasIconRight: string
  hasIconsLeft: string
  hasIconsRight: string
  hasName: string
  hasOverlap: string
  hasOverlay: string
  hasPasswordDiscover: string
  hasPatternDark: string
  hasPatternLight: string
  hasStatus: string
  hasTextAdmin: string
  hasTextAdminInvert: string
  hasTextCentered: string
  hasTextCenteredDesktop: string
  hasTextCenteredDesktopOnly: string
  hasTextCenteredFullhd: string
  hasTextCenteredMobile: string
  hasTextCenteredTablet: string
  hasTextCenteredTabletOnly: string
  hasTextCenteredTouch: string
  hasTextCenteredWidescreen: string
  hasTextCenteredWidescreenOnly: string
  hasTextCobalt: string
  hasTextCobaltInvert: string
  hasTextDanger: string
  hasTextDangerInvert: string
  hasTextDebug: string
  hasTextDebugInvert: string
  hasTextGrey: string
  hasTextGreyDark: string
  hasTextGreyLight: string
  hasTextGreyLighter: string
  hasTextInfo: string
  hasTextInfoInvert: string
  hasTextJustified: string
  hasTextJustifiedDesktop: string
  hasTextJustifiedDesktopOnly: string
  hasTextJustifiedFullhd: string
  hasTextJustifiedMobile: string
  hasTextJustifiedTablet: string
  hasTextJustifiedTabletOnly: string
  hasTextJustifiedTouch: string
  hasTextJustifiedWidescreen: string
  hasTextJustifiedWidescreenOnly: string
  hasTextLeft: string
  hasTextLeftDesktop: string
  hasTextLeftDesktopOnly: string
  hasTextLeftFullhd: string
  hasTextLeftMobile: string
  hasTextLeftTablet: string
  hasTextLeftTabletOnly: string
  hasTextLeftTouch: string
  hasTextLeftWidescreen: string
  hasTextLeftWidescreenOnly: string
  hasTextPrimary: string
  hasTextPrimaryInvert: string
  hasTextQuaternary: string
  hasTextQuaternaryInvert: string
  hasTextRight: string
  hasTextRightDesktop: string
  hasTextRightDesktopOnly: string
  hasTextRightFullhd: string
  hasTextRightMobile: string
  hasTextRightTablet: string
  hasTextRightTabletOnly: string
  hasTextRightTouch: string
  hasTextRightWidescreen: string
  hasTextRightWidescreenOnly: string
  hasTextSecondary: string
  hasTextSecondaryInvert: string
  hasTextSuccess: string
  hasTextSuccessInvert: string
  hasTextTertiary: string
  hasTextTertiaryInvert: string
  hasTextWarning: string
  hasTextWarningInvert: string
  hasTextWeightBold: string
  hasTextWeightExtrabold: string
  hasTextWeightLight: string
  hasTextWeightMedium: string
  hasTextWeightNormal: string
  hasTextWeightSemibold: string
  hasTextWhite: string
  hasTextWhiteInvert: string
  hasVariant: string
  help: string
  icon: string
  iconAndText: string
  iconList: string
  image: string
  input: string
  inputDynamicPlaceholder: string
  is0: string
  is0Desktop: string
  is0DesktopOnly: string
  is0Fullhd: string
  is0Mobile: string
  is0Tablet: string
  is0TabletOnly: string
  is0Touch: string
  is0Widescreen: string
  is0WidescreenOnly: string
  is1: string
  is10: string
  is10Desktop: string
  is10DesktopOnly: string
  is10Fullhd: string
  is10Mobile: string
  is10Tablet: string
  is10TabletOnly: string
  is10Touch: string
  is10Widescreen: string
  is10WidescreenOnly: string
  is11: string
  is11Desktop: string
  is11DesktopOnly: string
  is11Fullhd: string
  is11Mobile: string
  is11Tablet: string
  is11TabletOnly: string
  is11Touch: string
  is11Widescreen: string
  is11WidescreenOnly: string
  is12: string
  is12Desktop: string
  is12DesktopOnly: string
  is12Fullhd: string
  is12Mobile: string
  is12Tablet: string
  is12TabletOnly: string
  is12Touch: string
  is12Widescreen: string
  is12WidescreenOnly: string
  is1Desktop: string
  is1DesktopOnly: string
  is1Fullhd: string
  is1Mobile: string
  is1Tablet: string
  is1TabletOnly: string
  is1Touch: string
  is1Widescreen: string
  is1WidescreenOnly: string
  is2: string
  is2Desktop: string
  is2DesktopOnly: string
  is2Fullhd: string
  is2Mobile: string
  is2Tablet: string
  is2TabletOnly: string
  is2Touch: string
  is2Widescreen: string
  is2WidescreenOnly: string
  is3: string
  is3Desktop: string
  is3DesktopOnly: string
  is3Fullhd: string
  is3Mobile: string
  is3Tablet: string
  is3TabletOnly: string
  is3Touch: string
  is3Widescreen: string
  is3WidescreenOnly: string
  is4: string
  is4Desktop: string
  is4DesktopOnly: string
  is4Fullhd: string
  is4Mobile: string
  is4Tablet: string
  is4TabletOnly: string
  is4Touch: string
  is4Widescreen: string
  is4WidescreenOnly: string
  is5: string
  is5Desktop: string
  is5DesktopOnly: string
  is5Fullhd: string
  is5Mobile: string
  is5Tablet: string
  is5TabletOnly: string
  is5Touch: string
  is5Widescreen: string
  is5WidescreenOnly: string
  is6: string
  is6Desktop: string
  is6DesktopOnly: string
  is6Fullhd: string
  is6Mobile: string
  is6Tablet: string
  is6TabletOnly: string
  is6Touch: string
  is6Widescreen: string
  is6WidescreenOnly: string
  is7: string
  is7Desktop: string
  is7DesktopOnly: string
  is7Fullhd: string
  is7Mobile: string
  is7Tablet: string
  is7TabletOnly: string
  is7Touch: string
  is7Widescreen: string
  is7WidescreenOnly: string
  is8: string
  is8Desktop: string
  is8DesktopOnly: string
  is8Fullhd: string
  is8Mobile: string
  is8Tablet: string
  is8TabletOnly: string
  is8Touch: string
  is8Widescreen: string
  is8WidescreenOnly: string
  is9: string
  is9Desktop: string
  is9DesktopOnly: string
  is9Fullhd: string
  is9Mobile: string
  is9Tablet: string
  is9TabletOnly: string
  is9Touch: string
  is9Widescreen: string
  is9WidescreenOnly: string
  isActive: string
  isAdmin: string
  isAlignedBottom: string
  isAlignedCenter: string
  isAlignedCenterMobile: string
  isAlignedEnd: string
  isAlignedLeft: string
  isAlignedLeftMobile: string
  isAlignedRight: string
  isAlignedRightMobile: string
  isAlignedTop: string
  isAlternate: string
  isAncestor: string
  isAnimated: string
  isBlock: string
  isBlockDesktop: string
  isBlockDesktopOnly: string
  isBlockFullhd: string
  isBlockMobile: string
  isBlockTablet: string
  isBlockTabletOnly: string
  isBlockTouch: string
  isBlockWidescreen: string
  isBlockWidescreenOnly: string
  isBordered: string
  isBottom: string
  isBottomRight: string
  isBoxed: string
  isCapitalized: string
  isCentered: string
  isCenteredDesktop: string
  isCenteredMobile: string
  isCenteredTablet: string
  isChild: string
  isCircled: string
  isCircledAdmin: string
  isCircledCobalt: string
  isCircledDanger: string
  isCircledDebug: string
  isCircledGrey: string
  isCircledGreyDark: string
  isCircledGreyLight: string
  isCircledGreyLighter: string
  isCircledInfo: string
  isCircledPrimary: string
  isCircledQuaternary: string
  isCircledSecondary: string
  isCircledSuccess: string
  isCircledTertiary: string
  isCircledWarning: string
  isCircledWhite: string
  isClearfix: string
  isClipped: string
  isCobalt: string
  isDanger: string
  isDebug: string
  isDescendant: string
  isDesktop: string
  isDivider: string
  isDownload: string
  isEmpty: string
  isExpanded: string
  isFirst: string
  isFlat: string
  isFlatPrimary: string
  isFlatQuaternary: string
  isFlatSecondary: string
  isFlatTertiary: string
  isFlex: string
  isFlexDesktop: string
  isFlexDesktopOnly: string
  isFlexFullhd: string
  isFlexinessNavigation: string
  isFlexMobile: string
  isFlexTablet: string
  isFlexTabletOnly: string
  isFlexTouch: string
  isFlexWidescreen: string
  isFlexWidescreenOnly: string
  isFluid: string
  isFocused: string
  isFooterDesktop: string
  isFooterMobile: string
  isFooterSub: string
  isFourFifths: string
  isFourFifthsDesktop: string
  isFourFifthsFullhd: string
  isFourFifthsMobile: string
  isFourFifthsTablet: string
  isFourFifthsTouch: string
  isFourFifthsWidescreen: string
  isFourth: string
  isFull: string
  isFullDesktop: string
  isFullFullhd: string
  isFullheight: string
  isFullMobile: string
  isFullTablet: string
  isFullTouch: string
  isFullWidescreen: string
  isFullwidth: string
  isFullwidthMobile: string
  isGapless: string
  isGrey: string
  isGreyDark: string
  isGreyLight: string
  isGreyLighter: string
  isGrouped: string
  isGroupedCentered: string
  isGroupedMultiline: string
  isGroupedRight: string
  isHalf: string
  isHalfDesktop: string
  isHalfFullhd: string
  isHalfMobile: string
  isHalfTablet: string
  isHalfTouch: string
  isHalfWidescreen: string
  isHat: string
  isHidden: string
  isHiddenDesktop: string
  isHiddenDesktopOnly: string
  isHiddenFullhd: string
  isHiddenMobile: string
  isHiddenTablet: string
  isHiddenTabletOnly: string
  isHiddenTouch: string
  isHiddenWidescreen: string
  isHiddenWidescreenOnly: string
  isHighlighted: string
  isHorizontal: string
  isHoverable: string
  isHovered: string
  isHuge: string
  isInfo: string
  isInline: string
  isInlineBlock: string
  isInlineBlockDesktop: string
  isInlineBlockDesktopOnly: string
  isInlineBlockFullhd: string
  isInlineBlockMobile: string
  isInlineBlockTablet: string
  isInlineBlockTabletOnly: string
  isInlineBlockTouch: string
  isInlineBlockWidescreen: string
  isInlineBlockWidescreenOnly: string
  isInlineDesktop: string
  isInlineDesktopOnly: string
  isInlineFlex: string
  isInlineFlexDesktop: string
  isInlineFlexDesktopOnly: string
  isInlineFlexFullhd: string
  isInlineFlexMobile: string
  isInlineFlexTablet: string
  isInlineFlexTabletOnly: string
  isInlineFlexTouch: string
  isInlineFlexWidescreen: string
  isInlineFlexWidescreenOnly: string
  isInlineFullhd: string
  isInlineMobile: string
  isInlineTablet: string
  isInlineTabletOnly: string
  isInlineTouch: string
  isInlineWidescreen: string
  isInlineWidescreenOnly: string
  isInverted: string
  isInvertedMobile: string
  isInvisible: string
  isInvisibleDesktop: string
  isInvisibleDesktopOnly: string
  isInvisibleFullhd: string
  isInvisibleMobile: string
  isInvisibleTablet: string
  isInvisibleTabletOnly: string
  isInvisibleTouch: string
  isInvisibleWidescreen: string
  isInvisibleWidescreenOnly: string
  isItalic: string
  isJustifiedCenter: string
  isJustifiedCenterDesktop: string
  isJustifiedCenterDesktopOnly: string
  isJustifiedCenterFullhd: string
  isJustifiedCenterMobile: string
  isJustifiedCenterTablet: string
  isJustifiedCenterTabletOnly: string
  isJustifiedCenterTouch: string
  isJustifiedCenterWidescreen: string
  isJustifiedCenterWidescreenOnly: string
  isJustifiedEnd: string
  isJustifiedEndDesktop: string
  isJustifiedEndDesktopOnly: string
  isJustifiedEndFullhd: string
  isJustifiedEndMobile: string
  isJustifiedEndTablet: string
  isJustifiedEndTabletOnly: string
  isJustifiedEndTouch: string
  isJustifiedEndWidescreen: string
  isJustifiedEndWidescreenOnly: string
  isJustifiedStart: string
  isJustifiedStartDesktop: string
  isJustifiedStartDesktopOnly: string
  isJustifiedStartFullhd: string
  isJustifiedStartMobile: string
  isJustifiedStartTablet: string
  isJustifiedStartTabletOnly: string
  isJustifiedStartTouch: string
  isJustifiedStartWidescreen: string
  isJustifiedStartWidescreenOnly: string
  isLarge: string
  isLoading: string
  isLong: string
  isLowercase: string
  isMarginless: string
  isMedium: string
  isMegadropdownParent: string
  isMobile: string
  isMultiline: string
  isNarrow: string
  isNarrowDesktop: string
  isNarrowFullhd: string
  isNarrowMobile: string
  isNarrowTablet: string
  isNarrowTouch: string
  isNarrowWidescreen: string
  isNew: string
  isNormal: string
  isNowrap: string
  isNpm: string
  isOffset1: string
  isOffset10: string
  isOffset10Desktop: string
  isOffset10Fullhd: string
  isOffset10Mobile: string
  isOffset10Tablet: string
  isOffset10Touch: string
  isOffset10Widescreen: string
  isOffset11: string
  isOffset11Desktop: string
  isOffset11Fullhd: string
  isOffset11Mobile: string
  isOffset11Tablet: string
  isOffset11Touch: string
  isOffset11Widescreen: string
  isOffset12: string
  isOffset12Desktop: string
  isOffset12Fullhd: string
  isOffset12Mobile: string
  isOffset12Tablet: string
  isOffset12Touch: string
  isOffset12Widescreen: string
  isOffset1Desktop: string
  isOffset1Fullhd: string
  isOffset1Mobile: string
  isOffset1Tablet: string
  isOffset1Touch: string
  isOffset1Widescreen: string
  isOffset2: string
  isOffset2Desktop: string
  isOffset2Fullhd: string
  isOffset2Mobile: string
  isOffset2Tablet: string
  isOffset2Touch: string
  isOffset2Widescreen: string
  isOffset3: string
  isOffset3Desktop: string
  isOffset3Fullhd: string
  isOffset3Mobile: string
  isOffset3Tablet: string
  isOffset3Touch: string
  isOffset3Widescreen: string
  isOffset4: string
  isOffset4Desktop: string
  isOffset4Fullhd: string
  isOffset4Mobile: string
  isOffset4Tablet: string
  isOffset4Touch: string
  isOffset4Widescreen: string
  isOffset5: string
  isOffset5Desktop: string
  isOffset5Fullhd: string
  isOffset5Mobile: string
  isOffset5Tablet: string
  isOffset5Touch: string
  isOffset5Widescreen: string
  isOffset6: string
  isOffset6Desktop: string
  isOffset6Fullhd: string
  isOffset6Mobile: string
  isOffset6Tablet: string
  isOffset6Touch: string
  isOffset6Widescreen: string
  isOffset7: string
  isOffset7Desktop: string
  isOffset7Fullhd: string
  isOffset7Mobile: string
  isOffset7Tablet: string
  isOffset7Touch: string
  isOffset7Widescreen: string
  isOffset8: string
  isOffset8Desktop: string
  isOffset8Fullhd: string
  isOffset8Mobile: string
  isOffset8Tablet: string
  isOffset8Touch: string
  isOffset8Widescreen: string
  isOffset9: string
  isOffset9Desktop: string
  isOffset9Fullhd: string
  isOffset9Mobile: string
  isOffset9Tablet: string
  isOffset9Touch: string
  isOffset9Widescreen: string
  isOffsetFourFifths: string
  isOffsetFourFifthsDesktop: string
  isOffsetFourFifthsFullhd: string
  isOffsetFourFifthsMobile: string
  isOffsetFourFifthsTablet: string
  isOffsetFourFifthsTouch: string
  isOffsetFourFifthsWidescreen: string
  isOffsetHalf: string
  isOffsetHalfDesktop: string
  isOffsetHalfFullhd: string
  isOffsetHalfMobile: string
  isOffsetHalfTablet: string
  isOffsetHalfTouch: string
  isOffsetHalfWidescreen: string
  isOffsetOneFifth: string
  isOffsetOneFifthDesktop: string
  isOffsetOneFifthFullhd: string
  isOffsetOneFifthMobile: string
  isOffsetOneFifthTablet: string
  isOffsetOneFifthTouch: string
  isOffsetOneFifthWidescreen: string
  isOffsetOneQuarter: string
  isOffsetOneQuarterDesktop: string
  isOffsetOneQuarterFullhd: string
  isOffsetOneQuarterMobile: string
  isOffsetOneQuarterTablet: string
  isOffsetOneQuarterTouch: string
  isOffsetOneQuarterWidescreen: string
  isOffsetOneThird: string
  isOffsetOneThirdDesktop: string
  isOffsetOneThirdFullhd: string
  isOffsetOneThirdMobile: string
  isOffsetOneThirdTablet: string
  isOffsetOneThirdTouch: string
  isOffsetOneThirdWidescreen: string
  isOffsetThreeFifths: string
  isOffsetThreeFifthsDesktop: string
  isOffsetThreeFifthsFullhd: string
  isOffsetThreeFifthsMobile: string
  isOffsetThreeFifthsTablet: string
  isOffsetThreeFifthsTouch: string
  isOffsetThreeFifthsWidescreen: string
  isOffsetThreeQuarters: string
  isOffsetThreeQuartersDesktop: string
  isOffsetThreeQuartersFullhd: string
  isOffsetThreeQuartersMobile: string
  isOffsetThreeQuartersTablet: string
  isOffsetThreeQuartersTouch: string
  isOffsetThreeQuartersWidescreen: string
  isOffsetTwoFifths: string
  isOffsetTwoFifthsDesktop: string
  isOffsetTwoFifthsFullhd: string
  isOffsetTwoFifthsMobile: string
  isOffsetTwoFifthsTablet: string
  isOffsetTwoFifthsTouch: string
  isOffsetTwoFifthsWidescreen: string
  isOffsetTwoThirds: string
  isOffsetTwoThirdsDesktop: string
  isOffsetTwoThirdsFullhd: string
  isOffsetTwoThirdsMobile: string
  isOffsetTwoThirdsTablet: string
  isOffsetTwoThirdsTouch: string
  isOffsetTwoThirdsWidescreen: string
  isOneFifth: string
  isOneFifthDesktop: string
  isOneFifthFullhd: string
  isOneFifthMobile: string
  isOneFifthTablet: string
  isOneFifthTouch: string
  isOneFifthWidescreen: string
  isOneQuarter: string
  isOneQuarterDesktop: string
  isOneQuarterFullhd: string
  isOneQuarterMobile: string
  isOneQuarterTablet: string
  isOneQuarterTouch: string
  isOneQuarterWidescreen: string
  isOneThird: string
  isOneThirdDesktop: string
  isOneThirdFullhd: string
  isOneThirdMobile: string
  isOneThirdTablet: string
  isOneThirdTouch: string
  isOneThirdWidescreen: string
  isOrderReversed: string
  isOrderReversedMobile: string
  isOutlined: string
  isOverlay: string
  isPaddingless: string
  isParent: string
  isPlain: string
  isPositionnedBottom: string
  isPositionnedBottomMobile: string
  isPositionnedCenter: string
  isPositionnedCenterMobile: string
  isPositionnedLeft: string
  isPositionnedRight: string
  isPositionnedTop: string
  isPositionnedTopMobile: string
  isPrimary: string
  isPulledLeft: string
  isPulledRight: string
  isQuaternary: string
  isRadiusless: string
  isRight: string
  isRightAligned: string
  isRounded: string
  isSearching: string
  isSecond: string
  isSecondary: string
  isSectionTitle: string
  isShadowless: string
  isShort: string
  isSize1: string
  isSize1Desktop: string
  isSize1Fullhd: string
  isSize1Mobile: string
  isSize1Tablet: string
  isSize1Touch: string
  isSize1Widescreen: string
  isSize2: string
  isSize2Desktop: string
  isSize2Fullhd: string
  isSize2Mobile: string
  isSize2Tablet: string
  isSize2Touch: string
  isSize2Widescreen: string
  isSize3: string
  isSize3Desktop: string
  isSize3Fullhd: string
  isSize3Mobile: string
  isSize3Tablet: string
  isSize3Touch: string
  isSize3Widescreen: string
  isSize4: string
  isSize4Desktop: string
  isSize4Fullhd: string
  isSize4Mobile: string
  isSize4Tablet: string
  isSize4Touch: string
  isSize4Widescreen: string
  isSize5: string
  isSize5Desktop: string
  isSize5Fullhd: string
  isSize5Mobile: string
  isSize5Tablet: string
  isSize5Touch: string
  isSize5Widescreen: string
  isSize6: string
  isSize6Desktop: string
  isSize6Fullhd: string
  isSize6Mobile: string
  isSize6Tablet: string
  isSize6Touch: string
  isSize6Widescreen: string
  isSize7: string
  isSize7Desktop: string
  isSize7Fullhd: string
  isSize7Mobile: string
  isSize7Tablet: string
  isSize7Touch: string
  isSize7Widescreen: string
  isSize8: string
  isSize8Desktop: string
  isSize8Fullhd: string
  isSize8Mobile: string
  isSize8Tablet: string
  isSize8Touch: string
  isSize8Widescreen: string
  isSmall: string
  isSmallMobile: string
  isSpaced: string
  isSpacedAround: string
  isSpacedBetween: string
  isSpacedEvenly: string
  isStacked: string
  isStackedDesktop: string
  isStackedMobile: string
  isStackedTablet: string
  isStackedWidescreen: string
  isStatic: string
  isSticky: string
  isStretched: string
  isStriked: string
  isSuccess: string
  isTertiary: string
  isText: string
  isThreeFifths: string
  isThreeFifthsDesktop: string
  isThreeFifthsFullhd: string
  isThreeFifthsMobile: string
  isThreeFifthsTablet: string
  isThreeFifthsTouch: string
  isThreeFifthsWidescreen: string
  isThreeQuarters: string
  isThreeQuartersDesktop: string
  isThreeQuartersFullhd: string
  isThreeQuartersMobile: string
  isThreeQuartersTablet: string
  isThreeQuartersTouch: string
  isThreeQuartersWidescreen: string
  isTop: string
  isTransparent: string
  isTwoFifths: string
  isTwoFifthsDesktop: string
  isTwoFifthsFullhd: string
  isTwoFifthsMobile: string
  isTwoFifthsTablet: string
  isTwoFifthsTouch: string
  isTwoFifthsWidescreen: string
  isTwoThirds: string
  isTwoThirdsDesktop: string
  isTwoThirdsFullhd: string
  isTwoThirdsMobile: string
  isTwoThirdsTablet: string
  isTwoThirdsTouch: string
  isTwoThirdsWidescreen: string
  isUnboxed: string
  isUnderline: string
  isUnselectable: string
  isUp: string
  isUppercase: string
  isVariable: string
  isVcentered: string
  isVcenteredDesktop: string
  isVcenteredMobile: string
  isVcenteredTablet: string
  isVertical: string
  isVerticalMobile: string
  isVeryLong: string
  isVeryShort: string
  isWarning: string
  isWhite: string
  isWrapped: string
  label: string
  link: string
  login: string
  logo: string
  mainContent: string
  menu: string
  menuClose: string
  menuOpen: string
  navbar: string
  navbarBrand: string
  navbarCategoryTitle: string
  navbarDivider: string
  navbarDropdown: string
  navbarDropdownClose: string
  navbarDropdownSection: string
  navbarEnd: string
  navbarExtras: string
  navbarIcons: string
  navbarItem: string
  navbarItemAccordion: string
  navbarItemAccordionBack: string
  navbarItemAccordionContent: string
  navbarItemAccordionHeader: string
  navbarItemAccordionTitle: string
  navbarLink: string
  navbarLinks: string
  navbarMenu: string
  navbarStart: string
  navbarTitle: string
  paragraph: string
  partnersIcons: string
  row: string
  rows: string
  section: string
  select: string
  slidingLink: string
  small: string
  socialIcons: string
  spinAround: string
  subFooter: string
  subfooterLink: string
  subfooterTitle: string
  subtitle: string
  suptitle: string
  tag: string
  text: string
  tile: string
  tilesContainer: string
  title: string
  toggle: string
  user: string
  userMenu: string
}

export type ClassNames = keyof Styles

declare const styles: Styles

export default styles
