image: registry.glouton.int.nbyt.fr/commun/devops/ci/nodejs:centos7-node12

default:
  tags: ['paris']
  before_script:
    - npm ci
  cache:
    key: npm
    paths:
      - node_modules

stages:
  - test
  - deploy

.test:
  stage: test
  rules:
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME


lint:
  extends: ['.test']
  script:
    - npm run lint

test:
  extends: ['.test']
  script:
    - npm test

publish:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - npm version $CI_COMMIT_REF_NAME --allow-same-version --no-git-tag-version
    - npm run build
    - npm publish
